import React, { memo, useMemo, useState } from 'react';
import { Box } from '@mui/material';
import BaseSection from './BaseSection';
import ScoringOverviewMagnitude from '../../../scoringOverview/containers/ScoringOverviewMagnitude';
import ScoringOverviewLikelihood from '../../../scoringOverview/containers/ScoringOverviewLikelihood';
import CompanyScoringOverviewBubble from '../CompanyScoringOverviewBubble';
import CompanyScoringOverviewTotalChart from '../CompanyScoringOverviewTotalChart';
import CompanyScoringOverviewImpactList from '../CompanyScoringOverviewImpactList';
import CompanyGrowthLikelihoodSummary from './CompanyGrowthLikelihoodSummary';

const clamp = (value, min = 0, max = 100) => {
  const num = Number(value);
  if (!Number.isFinite(num)) {
    return 0;
  }
  return Math.max(min, Math.min(max, num));
};

const toScoreObj = (value) => {
  const num = Number(value);
  if (!Number.isFinite(num)) {
    return null;
  }
  return { score: num };
};

const average = (values) => {
  const numbers = values.filter(Number.isFinite);
  if (!numbers.length) {
    return null;
  }
  return numbers.reduce((acc, val) => acc + val, 0) / numbers.length;
};

const buildImpacts = (theoryOfChange = [], impactScoring = []) => {
  const scoringMap = new Map();
  impactScoring.forEach((item, index) => {
    const id = item.id || index + 1;
    scoringMap.set(id, item);
  });

  return theoryOfChange
    .map((impact, index) => {
      const id = impact.id || index + 1;
      const scoring = scoringMap.get(id) || {};
      const isPositive = !impact.type?.toLowerCase().includes('negative');

      const degreeOfChange = Number(scoring.degreeOfChange);
      const scalability = Number(scoring.scalability);
      const durationVal = Number(scoring.duration);
      const contribution = Number(scoring.contribution);
      const previousEvidence = Number(scoring.previousEvidence);
      const proximity = Number(scoring.proximity);
      const stakeholderSituation = Number(scoring.stakeholderSituation);

      const problemImportanceScore = average([
        Number(scoring.urgency),
        Number(scoring.irreversibility),
        Number(scoring.fairness),
        Number(scoring.interconnectedness),
        Number(scoring.problemImportance),
      ]);

      // Use exact CalculationService formula for magnitude:
      // importance = (problemImportance * 2/3 + stakeholderSituation * 1/3) * 20
      // howMuchSolved = ((1 + degreeOfChange * 9/100) * 6/7 + duration * 2/7) / 10
      // contributionFactor = (1 + contribution * 9/100) / 10
      // magnitude = importance * howMuchSolved * (sizeOfStakeholders / 10) * contributionFactor
      const importance = ((problemImportanceScore || 0) * 2 / 3 +
        (stakeholderSituation || 0) * 1 / 3) * 20;
      const howMuchSolved = ((1 + (degreeOfChange || 0) * 9 / 100) * 6 / 7 +
        (durationVal || 0) * 2 / 7) / 10;
      const contributionFactor = (1 + (contribution || 0) * 9 / 100) / 10;
      const baseMagnitude = importance * howMuchSolved *
        ((scalability || 0) / 10) * contributionFactor;
      // Magnitude is always positive (charts handle display of negative impacts)
      const magnitude = Math.max(0, baseMagnitude);

      // Use exact CalculationService formula for likelihood:
      // For positive with indicators: (previousEvidence + proximity + avgNoisiness + avgValidation) * 5
      // For positive without indicators: (previousEvidence + proximity) * 10
      // For negative: previousEvidence * 20
      let likelihood;
      if (isPositive) {
        const indicators = Array.isArray(scoring.indicators) ? scoring.indicators : [];
        const noisinessValues = indicators
          .map(ind => Number(ind.noisiness))
          .filter(Number.isFinite);
        if (noisinessValues.length > 0) {
          const avgNoisiness = noisinessValues.reduce((a, b) => a + b, 0) / noisinessValues.length;
          const avgValidation = 3; // Default validation score (not generated by AI)
          likelihood = ((previousEvidence || 0) + (proximity || 0) + avgNoisiness + avgValidation) * 5;
        } else {
          likelihood = ((previousEvidence || 0) + (proximity || 0)) * 10;
        }
      } else {
        likelihood = (previousEvidence || 0) * 20;
      }
      likelihood = clamp(likelihood);

      // Score is always positive - charts and totals handle negative display/subtraction
      const score = Math.round((magnitude * likelihood / 100) * 10) / 10;

      const indicatorScores = Array.isArray(scoring.indicators)
        ? scoring.indicators.map((indicator, idx) => ({
          indicator: { id: indicator.id || idx + 1 },
          noisiness: toScoreObj(indicator.noisiness),
          validation: toScoreObj(indicator.validation),
        }))
        : [];

      const scoringEntry = {
        magnitude,
        likelihood,
        score,
        degreeOfChange: Number.isFinite(degreeOfChange) ? degreeOfChange : 0,
        contribution: Number.isFinite(contribution) ? contribution : 0,
        duration: isPositive ? toScoreObj(durationVal) : null,
        durationNegative: !isPositive ? toScoreObj(durationVal) : null,
        previousEvidence: isPositive ? toScoreObj(previousEvidence) : null,
        previousEvidenceNegative: !isPositive ? toScoreObj(previousEvidence) : null,
        proximity: toScoreObj(scoring.proximity),
        sizeOfStakeholders: isPositive ? toScoreObj(scalability) : null,
        sizeOfStakeholdersNegative: !isPositive ? toScoreObj(scalability) : null,
        stakeholderSituation: isPositive ? toScoreObj(scoring.stakeholderSituation) : null,
        stakeholderSituationNegative: !isPositive ? toScoreObj(scoring.stakeholderSituation) : null,
        problemImportance: isPositive ? toScoreObj(problemImportanceScore) : null,
        problemImportanceNegative: !isPositive ? toScoreObj(problemImportanceScore) : null,
        indicatorScores,
      };

      if (!Number.isFinite(score)) {
        return null;
      }

      return {
        id,
        name: impact.title || `Impact area ${index + 1}`,
        positive: isPositive,
        createdAt: new Date().toISOString(),
        scoring: [scoringEntry],
      };
    })
    .filter(Boolean)
    .filter(item => Number.isFinite(item.scoring.at(-1).score));
};

const CompanyScoringOverviewSection = ({ data }) => {
  const impacts = useMemo(
    () => buildImpacts(data?.theory_of_change || [], data?.impact_scoring || []),
    [data?.theory_of_change, data?.impact_scoring]
  );
  const [selected, setSelected] = useState(impacts);
  const [details, setDetails] = useState(true);

  React.useEffect(() => {
    setSelected(impacts);
  }, [impacts]);

  const toggleDetails = () => {
    setSelected(impacts);
    setDetails(val => !val);
  };

  if (!impacts.length) {
    return null;
  }

  return (
    <BaseSection
      title="Impact scoring overview"
      subtitle="AI-derived impact magnitude and likelihood across impact areas"
    >
      <Box display='flex' gap={3}>
        <Box sx={{ flex: '300 1 0', maxWidth: 300, minWidth: 200 }}>
          <Box display='flex' flexDirection='column' gap={3}>
            <ScoringOverviewMagnitude selected={selected} />
            <ScoringOverviewLikelihood selected={selected} />
            <CompanyGrowthLikelihoodSummary data={data} />
          </Box>
        </Box>
        <Box sx={{ flex: '1004 1 0' }} display='flex' flexDirection='column' gap={3}>
          <Box>
            <CompanyScoringOverviewTotalChart
              selected={selected}
              growthScore={data?.growth_composite_score}
            />
          </Box>
          <Box display='flex' gap={3}>
            <Box sx={{ flex: '600 1 0', maxWidth: 600, minWidth: 350 }}>
              <CompanyScoringOverviewBubble impacts={impacts} selected={selected} details={details} />
            </Box>
            <Box sx={{ flex: '380 1 0', minWidth: 220 }}>
              <CompanyScoringOverviewImpactList
                impacts={impacts}
                selected={selected}
                setSelected={setSelected}
                details={details}
                toggleDetails={toggleDetails}
              />
            </Box>
          </Box>
        </Box>
      </Box>
    </BaseSection>
  );
};

export default memo(CompanyScoringOverviewSection);
