package io.ventureplatform.entity.enums;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Getter;

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
@Getter
public enum Geography implements DeserializableEnum {
  GLOBAL("Global", GeographicType.REGION, null),
  AFRICA("Africa", GeographicType.CONTINENT, null),
  ALGERIA("Algeria", GeographicType.COUNTRY, "DZ"),
  ANGOLA("Angola", GeographicType.COUNTRY, "AO"),
  BENIN("Benin", GeographicType.COUNTRY, "BJ"),
  BOTSWANA("Botswana", GeographicType.COUNTRY, "BW"),
  BURKINA_FASO("Burkina Faso", GeographicType.COUNTRY, "BF"),
  BURUNDI("Burundi", GeographicType.COUNTRY, "BI"),
  CABO_VERDE("Cabo Verde/Cape Verde", GeographicType.COUNTRY, "CV"),
  CAMEROON("Cameroon", GeographicType.COUNTRY, "CM"),
  CENTRAL_AFRICAN_REPUBLIC("Central African Republic", GeographicType.COUNTRY, "CF"),
  CHAD("Chad", GeographicType.COUNTRY, "TD"),
  COMOROS("Comoros", GeographicType.COUNTRY, "KM"),
  CONGO("Congo/Republic of the Congo", GeographicType.COUNTRY, "CG"),
  CONGO_DEMOCRATIC_REPUBLIC("Democratic Republic of the Congo", GeographicType.COUNTRY, "CD"),
  DJIBOUTI("Djibouti", GeographicType.COUNTRY, "DJ"),
  EGYPT("Egypt", GeographicType.COUNTRY, "EG"),
  EQUATORIAL_GUINEA("Equatorial Guinea", GeographicType.COUNTRY, "GQ"),
  ERITREA("Eritrea", GeographicType.COUNTRY, "ER"),
  ESWATINI("Eswatini (formerly Swaziland)", GeographicType.COUNTRY, "SZ"),
  ETHIOPIA("Ethiopia", GeographicType.COUNTRY, "ET"),
  GABON("Gabon", GeographicType.COUNTRY, "GA"),
  GAMBIA("Gambia, The", GeographicType.COUNTRY, "GM"),
  GHANA("Ghana", GeographicType.COUNTRY, "GH"),
  GUINEA("Guinea", GeographicType.COUNTRY, "GN"),
  GUINEA_BISSAU("Guinea-Bissau", GeographicType.COUNTRY, "GW"),
  IVORY_COAST("Ivory Coast/Republic of Cote d'Ivoire", GeographicType.COUNTRY, "CI"),
  KENYA("Kenya", GeographicType.COUNTRY, "KE"),
  LESOTHO("Lesotho", GeographicType.COUNTRY, "LS"),
  LIBERIA("Liberia", GeographicType.COUNTRY, "LR"),
  LIBYA("Libya", GeographicType.COUNTRY, "LY"),
  MADAGASCAR("Madagascar", GeographicType.COUNTRY, "MG"),
  MALAWI("Malawi", GeographicType.COUNTRY, "MW"),
  MALI("Mali", GeographicType.COUNTRY, "ML"),
  MAURITANIA("Mauritania", GeographicType.COUNTRY, "MR"),
  MAURITIUS("Mauritius", GeographicType.COUNTRY, "MU"),
  MOROCCO("Morocco", GeographicType.COUNTRY, "MA"),
  MOZAMBIQUE("Mozambique", GeographicType.COUNTRY, "MZ"),
  NAMIBIA("Namibia", GeographicType.COUNTRY, "NA"),
  NIGER("Niger", GeographicType.COUNTRY, "NE"),
  NIGERIA("Nigeria", GeographicType.COUNTRY, "NG"),
  RWANDA("Rwanda", GeographicType.COUNTRY, "RW"),
  SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", GeographicType.COUNTRY, "ST"),
  SENEGAL("Senegal", GeographicType.COUNTRY, "SN"),
  SEYCHELLES("Seychelles", GeographicType.COUNTRY, "SC"),
  SIERRA_LEONE("Sierra Leone", GeographicType.COUNTRY, "SL"),
  SOMALIA("Somalia", GeographicType.COUNTRY, "SO"),
  SOUTH_AFRICA("South Africa", GeographicType.COUNTRY, "ZA"),
  SOUTH_SUDAN("South Sudan", GeographicType.COUNTRY, "SS"),
  SUDAN("Sudan", GeographicType.COUNTRY, "SD"),
  TANZANIA("Tanzania", GeographicType.COUNTRY, "TZ"),
  TOGO("Togo", GeographicType.COUNTRY, "TG"),
  TUNISIA("Tunisia", GeographicType.COUNTRY, "TN"),
  UGANDA("Uganda", GeographicType.COUNTRY, "UG"),
  ZAMBIA("Zambia", GeographicType.COUNTRY, "ZM"),
  ZIMBABWE("Zimbabwe", GeographicType.COUNTRY, "ZW"),
  CANARY_ISLANDS("Canary Islands", GeographicType.TERRITORY, null),
  CEUTA("Ceuta", GeographicType.TERRITORY, null),
  FRENCH_SOUTHERN_AND_ANTARCTIC_LANDS("French Southern and Antarctic Lands", GeographicType.TERRITORY, "TF"),
  MADEIRA("Madeira", GeographicType.TERRITORY, null),
  MAYOTTE("Mayotte", GeographicType.TERRITORY, "YT"),
  MELILLA("Melilla", GeographicType.TERRITORY, null),
  PELAGIE_ISLANDS("Pelagie Islands", GeographicType.TERRITORY, null),
  PLAZAS_DE_SOBERANIA("Plazas de Soberania", GeographicType.TERRITORY, null),
  REUNION("Reunion", GeographicType.TERRITORY, "RE"),
  SAINT_HELENA("Saint Helena, Ascension and Tristan da Cunha", GeographicType.TERRITORY, "SH"),
  SOCOTRA_ARCHIPELAGO("Socotra Archipelago", GeographicType.TERRITORY, null),
  ANTARCTICA("Antarctica", GeographicType.CONTINENT, "AQ"),
  ASIA("Asia", GeographicType.CONTINENT, null),
  AFGHANISTAN("Afghanistan", GeographicType.COUNTRY, "AF"),
  ARMENIA("Armenia", GeographicType.COUNTRY, "AM"),
  AZERBAIJAN("Azerbaijan", GeographicType.COUNTRY, "AZ"),
  BAHRAIN("Bahrain", GeographicType.COUNTRY, "BH"),
  BANGLADESH("Bangladesh", GeographicType.COUNTRY, "BD"),
  BHUTAN("Bhutan", GeographicType.COUNTRY, "BT"),
  BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory", GeographicType.TERRITORY, "IO"),
  BRUNEI("Brunei", GeographicType.COUNTRY, "BN"),
  CAMBODIA("Cambodia", GeographicType.COUNTRY, "KH"),
  CHINA("China", GeographicType.COUNTRY, "CN"),
  GEORGIA("Georgia", GeographicType.COUNTRY, "GE"),
  HONG_KONG("Hong Kong", GeographicType.COUNTRY, "HK"),
  INDIA("India", GeographicType.COUNTRY, "IN"),
  INDONESIA("Indonesia", GeographicType.COUNTRY, "ID"),
  IRAN("Iran", GeographicType.COUNTRY, "IR"),
  IRAQ("Iraq", GeographicType.COUNTRY, "IQ"),
  ISRAEL("Israel", GeographicType.COUNTRY, "IL"),
  JAPAN("Japan", GeographicType.COUNTRY, "JP"),
  JORDAN("Jordan", GeographicType.COUNTRY, "JO"),
  KAZAKHSTAN("Kazakhstan", GeographicType.COUNTRY, "KZ"),
  KUWAIT("Kuwait", GeographicType.COUNTRY, "KW"),
  KYRGYZSTAN("Kyrgyzstan", GeographicType.COUNTRY, "KG"),
  LAOS("Laos", GeographicType.COUNTRY, "LA"),
  LEBANON("Lebanon", GeographicType.COUNTRY, "LB"),
  MACAU("Macau", GeographicType.TERRITORY, "MO"),
  MALAYSIA("Malaysia", GeographicType.COUNTRY, "MY"),
  MALDIVES("Maldives", GeographicType.COUNTRY, "MV"),
  MONGOLIA("Mongolia", GeographicType.COUNTRY, "MN"),
  MYANMAR("Myanmar", GeographicType.COUNTRY, "MM"),
  NEPAL("Nepal", GeographicType.COUNTRY, "NP"),
  NORTH_KOREA("North Korea (Democratic People's Republic of Korea)", GeographicType.COUNTRY, "KP"),
  OMAN("Oman", GeographicType.COUNTRY, "OM"),
  PAKISTAN("Pakistan", GeographicType.COUNTRY, "PK"),
  PALESTINE("Palestine", GeographicType.COUNTRY, "PS"),
  PHILIPPINES("Philippines", GeographicType.COUNTRY, "PH"),
  QATAR("Qatar", GeographicType.COUNTRY, "QA"),
  SAUDI_ARABIA("Saudi Arabia", GeographicType.COUNTRY, "SA"),
  SINGAPORE("Singapore", GeographicType.COUNTRY, "SG"),
  SOUTH_KOREA("South Korea (Republic of Korea)", GeographicType.COUNTRY, "KR"),
  SRI_LANKA("Sri Lanka", GeographicType.COUNTRY, "LK"),
  SYRIA("Syria", GeographicType.COUNTRY, "SY"),
  TAIWAN("Taiwan", GeographicType.COUNTRY, "TW"),
  TAJIKISTAN("Tajikistan", GeographicType.COUNTRY, "TJ"),
  THAILAND("Thailand", GeographicType.COUNTRY, "TH"),
  TIMOR_LESTE("Timor-Leste/East Timor", GeographicType.COUNTRY, "TL"),
  TURKMENISTAN("Turkmenistan", GeographicType.COUNTRY, "TM"),
  UNITED_ARAB_EMIRATES("United Arab Emirates", GeographicType.COUNTRY, "AE"),
  UZBEKISTAN("Uzbekistan", GeographicType.COUNTRY, "UZ"),
  VIETNAM("Vietnam", GeographicType.COUNTRY, "VN"),
  YEMEN("Yemen", GeographicType.COUNTRY, "YE"),
  OCEANIA("Oceania", GeographicType.CONTINENT, null),
  AUSTRALIA("Australia", GeographicType.COUNTRY, "AU"),
  FIJI("Fiji", GeographicType.COUNTRY, "FJ"),
  KIRIBATI("Kiribati", GeographicType.COUNTRY, "KI"),
  MARSHALL_ISLANDS("Marshall Islands", GeographicType.COUNTRY, "MH"),
  MICRONESIA("Micronesia (The Federated States of)", GeographicType.COUNTRY, "FM"),
  NAURU("Nauru", GeographicType.COUNTRY, "NR"),
  NEW_ZEALAND("New Zealand", GeographicType.COUNTRY, "NZ"),
  PALAU("Palau", GeographicType.COUNTRY, "PW"),
  PAPUA_NEW_GUINEA("Papua New Guinea", GeographicType.COUNTRY, "PG"),
  SAMOA("Samoa", GeographicType.COUNTRY, "WS"),
  SOLOMON_ISLANDS("Solomon Islands", GeographicType.COUNTRY, "SB"),
  TONGA("Tonga", GeographicType.COUNTRY, "TO"),
  TUVALU("Tuvalu", GeographicType.COUNTRY, "TV"),
  VANUATU("Vanuatu", GeographicType.COUNTRY, "VU"),
  AMERICAN_SAMOA("American Samoa", GeographicType.TERRITORY, "AS"),
  ASHMORE_AND_CARTIER_ISLANDS("Ashmore and Cartier Islands", GeographicType.TERRITORY, null),
  BAKER_ISLAND("Baker Island", GeographicType.TERRITORY, null),
  COOK_ISLANDS("Cook Islands", GeographicType.TERRITORY, "CK"),
  CORAL_SEA_ISLANDS("Coral Sea Islands", GeographicType.TERRITORY, null),
  EASTER_ISLAND("Easter Island", GeographicType.TERRITORY, null),
  FRENCH_POLYNESIA("French Polynesia", GeographicType.TERRITORY, "PF"),
  GALAPAGOS_ISLANDS("Galapagos Islands", GeographicType.TERRITORY, null),
  GUAM("Guam", GeographicType.TERRITORY, "GU"),
  HOWLAND_ISLAND("Howland Island", GeographicType.TERRITORY, null),
  JARVIS_ISLAND("Jarvis Island", GeographicType.TERRITORY, null),
  JOHNSTON_ATOLL("Johnston Atoll", GeographicType.TERRITORY, null),
  KINGMAN_REEF("Kingman Reef", GeographicType.TERRITORY, null),
  MIDWAY_ATOLL("Midway Atoll", GeographicType.TERRITORY, null),
  NEW_CALEDONIA("New Caledonia", GeographicType.TERRITORY, "NC"),
  NIUE("Niue", GeographicType.TERRITORY, "NU"),
  NORFOLK_ISLAND("Norfolk Island", GeographicType.TERRITORY, "NF"),
  NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands", GeographicType.TERRITORY, "MP"),
  PALMYRA_ATOLL("Palmyra Atoll", GeographicType.TERRITORY, null),
  PAPUA("Papua (Indonesia)", GeographicType.TERRITORY, null),
  PITCAIRN_ISLANDS("Pitcairn Islands", GeographicType.TERRITORY, "PN"),
  SAN_ANDRES_AND_PROVIDENCIA("San Andrés and Providencia", GeographicType.TERRITORY, null),
  TOKELAU("Tokelau", GeographicType.TERRITORY, "TK"),
  WAKE_ISLAND("Wake Island", GeographicType.TERRITORY, null),
  WALLIS_AND_FUTUNA("Wallis and Futuna", GeographicType.TERRITORY, "WF"),
  WEST_PAPUA("West Papua", GeographicType.TERRITORY, null),
  EUROPE("Europe", GeographicType.CONTINENT, null),
  ALBANIA("Albania", GeographicType.COUNTRY, "AL"),
  ANDORRA("Andorra", GeographicType.COUNTRY, "AD"),
  AUSTRIA("Austria", GeographicType.COUNTRY, "AT"),
  BELARUS("Belarus", GeographicType.COUNTRY, "BY"),
  BELGIUM("Belgium", GeographicType.COUNTRY, "BE"),
  BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", GeographicType.COUNTRY, "BA"),
  BULGARIA("Bulgaria", GeographicType.COUNTRY, "BG"),
  CROATIA("Croatia", GeographicType.COUNTRY, "HR"),
  CYPRUS("Cyprus", GeographicType.COUNTRY, "CY"),
  CZECH_REPUBLIC("Czechia/Czech Republic", GeographicType.COUNTRY, "CZ"),
  DENMARK("Denmark", GeographicType.COUNTRY, "DK"),
  ESTONIA("Estonia", GeographicType.COUNTRY, "EE"),
  FINLAND("Finland", GeographicType.COUNTRY, "FI"),
  FRANCE("France", GeographicType.COUNTRY, "FR"),
  GERMANY("Germany", GeographicType.COUNTRY, "DE"),
  GREECE("Greece", GeographicType.COUNTRY, "GR"),
  HUNGARY("Hungary", GeographicType.COUNTRY, "HU"),
  ICELAND("Iceland", GeographicType.COUNTRY, "IS"),
  IRELAND("Ireland", GeographicType.COUNTRY, "IE"),
  ITALY("Italy", GeographicType.COUNTRY, "IT"),
  LATVIA("Latvia", GeographicType.COUNTRY, "LV"),
  LIECHTENSTEIN("Liechtenstein", GeographicType.COUNTRY, "LI"),
  LITHUANIA("Lithuania", GeographicType.COUNTRY, "LT"),
  LUXEMBOURG("Luxembourg", GeographicType.COUNTRY, "LU"),
  MALTA("Malta", GeographicType.COUNTRY, "MT"),
  MOLDOVA("Moldova", GeographicType.COUNTRY, "MD"),
  MONACO("Monaco", GeographicType.COUNTRY, "MC"),
  MONTENEGRO("Montenegro", GeographicType.COUNTRY, "ME"),
  NETHERLANDS("Netherlands", GeographicType.COUNTRY, "NL"),
  NORTH_MACEDONIA("North Macedonia", GeographicType.COUNTRY, "MK"),
  NORWAY("Norway", GeographicType.COUNTRY, "NO"),
  POLAND("Poland", GeographicType.COUNTRY, "PL"),
  PORTUGAL("Portugal", GeographicType.COUNTRY, "PT"),
  ROMANIA("Romania", GeographicType.COUNTRY, "RO"),
  RUSSIA("Russia", GeographicType.COUNTRY, "RU"),
  SAN_MARINO("San Marino", GeographicType.COUNTRY, "SM"),
  SERBIA("Serbia", GeographicType.COUNTRY, "RS"),
  SLOVAKIA("Slovakia", GeographicType.COUNTRY, "SK"),
  SLOVENIA("Slovenia", GeographicType.COUNTRY, "SI"),
  SPAIN("Spain", GeographicType.COUNTRY, "ES"),
  SWEDEN("Sweden", GeographicType.COUNTRY, "SE"),
  SWITZERLAND("Switzerland", GeographicType.COUNTRY, "CH"),
  TURKEY("Turkey", GeographicType.COUNTRY, "TR"),
  UKRAINE("Ukraine", GeographicType.COUNTRY, "UA"),
  UNITED_KINGDOM("United Kingdom", GeographicType.COUNTRY, "GB"),
  VATICAN_CITY("Vatican City (Holy See)", GeographicType.COUNTRY, "VA"),
  ALAND_ISLANDS("Aland Islands", GeographicType.TERRITORY, "AX"),
  CHANNEL_ISLANDS("Channel Islands", GeographicType.TERRITORY, null),
  FAROE_ISLANDS("Faroe Islands", GeographicType.TERRITORY, "FO"),
  GIBRALTAR("Gibraltar", GeographicType.TERRITORY, "GI"),
  GUERNSEY("Guernsey", GeographicType.TERRITORY, "GG"),
  ISLE_OF_MAN("Isle of Man", GeographicType.TERRITORY, "IM"),
  JERSEY("Jersey", GeographicType.TERRITORY, "JE"),
  KOSOVO("Kosovo", GeographicType.TERRITORY, null),
  NORTHERN_IRELAND("Northern Ireland", GeographicType.TERRITORY, null),
  SVALBARD("Svalbard", GeographicType.TERRITORY, "SJ"),
  NORTH_AMERICA("North America", GeographicType.CONTINENT, null),
  ANTIGUA_AND_BARBUDA("Antigua and Barbuda", GeographicType.COUNTRY, "AG"),
  BAHAMAS("Bahamas", GeographicType.COUNTRY, "BS"),
  BARBADOS("Barbados", GeographicType.COUNTRY, "BB"),
  BELIZE("Belize", GeographicType.COUNTRY, "BZ"),
  CANADA("Canada", GeographicType.COUNTRY, "CA"),
  COSTA_RICA("Costa Rica", GeographicType.COUNTRY, "CR"),
  CUBA("Cuba", GeographicType.COUNTRY, "CU"),
  DOMINICA("Dominica", GeographicType.COUNTRY, "DM"),
  DOMINICAN_REPUBLIC("Dominican Republic", GeographicType.COUNTRY, "DO"),
  EL_SALVADOR("El Salvador", GeographicType.COUNTRY, "SV"),
  GRENADA("Grenada", GeographicType.COUNTRY, "GD"),
  GUATEMALA("Guatemala", GeographicType.COUNTRY, "GT"),
  HAITI("Haiti", GeographicType.COUNTRY, "HT"),
  HONDURAS("Honduras", GeographicType.COUNTRY, "HN"),
  JAMAICA("Jamaica", GeographicType.COUNTRY, "JM"),
  MEXICO("Mexico", GeographicType.COUNTRY, "MX"),
  NICARAGUA("Nicaragua", GeographicType.COUNTRY, "NI"),
  PANAMA("Panama", GeographicType.COUNTRY, "PA"),
  SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", GeographicType.COUNTRY, "KN"),
  SAINT_LUCIA("Saint Lucia", GeographicType.COUNTRY, "LC"),
  SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", GeographicType.COUNTRY, "VC"),
  TRINIDAD_AND_TOBAGO("Trinidad and Tobago", GeographicType.COUNTRY, "TT"),
  UNITED_STATES_OF_AMERICA("United States of America", GeographicType.COUNTRY, "US"),
  ANGUILLA("Anguilla", GeographicType.TERRITORY, "AI"),
  ARUBA("Aruba", GeographicType.TERRITORY, "AW"),
  BERMUDA("Bermuda", GeographicType.TERRITORY, "BM"),
  BONAIRE("Bonaire", GeographicType.TERRITORY, "BQ"),
  BRITISH_VIRGIN_ISLANDS("British Virgin Islands", GeographicType.TERRITORY, "VG"),
  CAYMAN_ISLANDS("Cayman Islands", GeographicType.TERRITORY, "KY"),
  CLIPPERTON_ISLAND("Clipperton Island", GeographicType.TERRITORY, null),
  CURACAO("Curacao", GeographicType.TERRITORY, "CW"),
  GREENLAND("Greenland", GeographicType.TERRITORY, "GL"),
  GUADELOUPE("Guadeloupe", GeographicType.TERRITORY, "GP"),
  MARTINIQUE("Martinique", GeographicType.TERRITORY, "MQ"),
  MONTSERRAT("Montserrat", GeographicType.TERRITORY, "MS"),
  NAVASSA_ISLAND("Navassa Island", GeographicType.TERRITORY, null),
  PUERTO_RICO("Puerto Rico", GeographicType.TERRITORY, "PR"),
  SABA("Saba", GeographicType.TERRITORY, null),
  SAINT_BARTHELEMY("Saint Barthélemy", GeographicType.TERRITORY, "BL"),
  SAINT_MARTIN("Saint Martin", GeographicType.TERRITORY, "MF"),
  SAINT_PIERRE_AND_MIQUELON("Saint Pierre and Miquelon", GeographicType.TERRITORY, "PM"),
  SINT_EUSTATIUS("Sint Eustatius", GeographicType.TERRITORY, null),
  SINT_MAARTEN("Sint Maarten", GeographicType.TERRITORY, "SX"),
  TURKS_AND_CAICOS("Turks and Caicos", GeographicType.TERRITORY, "TC"),
  US_VIRGIN_ISLANDS("US Virgin Islands", GeographicType.TERRITORY, "VI"),
  SOUTH_AMERICA("South America", GeographicType.CONTINENT, null),
  ARGENTINA("Argentina", GeographicType.COUNTRY, "AR"),
  BOLIVIA("Bolivia", GeographicType.COUNTRY, "BO"),
  BRAZIL("Brazil", GeographicType.COUNTRY, "BR"),
  CHILE("Chile", GeographicType.COUNTRY, "CL"),
  COLOMBIA("Colombia", GeographicType.COUNTRY, "CO"),
  ECUADOR("Ecuador", GeographicType.COUNTRY, "EC"),
  GUYANA("Guyana", GeographicType.COUNTRY, "GY"),
  PARAGUAY("Paraguay", GeographicType.COUNTRY, "PY"),
  PERU("Peru", GeographicType.COUNTRY, "PE"),
  SURINAME("Suriname", GeographicType.COUNTRY, "SR"),
  URUGUAY("Uruguay", GeographicType.COUNTRY, "UY"),
  VENEZUELA("Venezuela", GeographicType.COUNTRY, "VE"),
  BOUVET_ISLAND("Bouvet Island", GeographicType.TERRITORY, "BV"),
  FALKLAND_ISLANDS("Falkland Islands", GeographicType.TERRITORY, "FK"),
  FRENCH_GUIANA("French Guinea", GeographicType.TERRITORY, "GF"),
  NUEVA_ESPARTA("Nueva Esparta", GeographicType.TERRITORY, null),
  SOUTH_GEORGIA("South Georgia and the South Sandwich Islands", GeographicType.TERRITORY, "GS");

  private final String name;
  private final String title;
  private final String type;
  private final GeographicType geographicType;
  private final String code;

  Geography(String title, GeographicType geographicType, String code) {
    this.name = this.name();
    this.title = title;
    this.type = this.getClass().getSimpleName();
    this.geographicType = geographicType;
    this.code = code;
  }
}
