package io.ventureplatform.entity.enums;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Getter;

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
@Getter
public enum Industry {
  ARCHIVING_SERVICE("Archiving Service", IndustryGroup.ADMINISTRATIVE_SERVICES),
  CALL_CENTER("Call Center", IndustryGroup.ADMINISTRATIVE_SERVICES),
  COLLECTION_AGENCY("Collection Agency", IndustryGroup.ADMINISTRATIVE_SERVICES),
  COLLEGE_RECRUITING("College Recruiting", IndustryGroup.ADMINISTRATIVE_SERVICES),
  COURIER_SERVICE("Courier Service", IndustryGroup.ADMINISTRATIVE_SERVICES),
  DEBT_COLLECTIONS("Debt Collections", IndustryGroup.ADMINISTRATIVE_SERVICES),
  DELIVERY("Delivery", IndustryGroup.ADMINISTRATIVE_SERVICES),
  DOCUMENT_PREPARATION("Document Preparation", IndustryGroup.ADMINISTRATIVE_SERVICES),
  EMPLOYEE_BENEFITS("Employee Benefits", IndustryGroup.ADMINISTRATIVE_SERVICES),
  EXTERMINATION_SERVICE("Extermination Service", IndustryGroup.ADMINISTRATIVE_SERVICES),
  FACILITIES_SUPPORT_SERVICES("Facilities Support Services", IndustryGroup.ADMINISTRATIVE_SERVICES),
  HOUSEKEEPING_SERVICE("Housekeeping Service", IndustryGroup.ADMINISTRATIVE_SERVICES),
  HUMAN_RESOURCES("Human Resources", IndustryGroup.ADMINISTRATIVE_SERVICES),
  KNOWLEDGE_MANAGEMENT("Knowledge Management", IndustryGroup.ADMINISTRATIVE_SERVICES),
  OFFICE_ADMINISTRATION("Office Administration", IndustryGroup.ADMINISTRATIVE_SERVICES),
  PACKAGING_SERVICES("Packaging Services", IndustryGroup.ADMINISTRATIVE_SERVICES),
  PHYSICAL_SECURITY("Physical Security", IndustryGroup.ADMINISTRATIVE_SERVICES),
  PROJECT_MANAGEMENT("Project Management", IndustryGroup.ADMINISTRATIVE_SERVICES),
  STAFFING_AGENCY("Staffing Agency", IndustryGroup.ADMINISTRATIVE_SERVICES),
  TRADE_SHOWS("Trade Shows", IndustryGroup.ADMINISTRATIVE_SERVICES),
  VIRTUAL_WORKFORCE("Virtual Workforce", IndustryGroup.ADMINISTRATIVE_SERVICES),
  AD_EXCHANGE("Ad Exchange", IndustryGroup.ADVERTISING),
  AD_NETWORK("Ad Network", IndustryGroup.ADVERTISING),
  AD_RETARGETING("Ad Retargeting", IndustryGroup.ADVERTISING),
  AD_SERVER("Ad Server", IndustryGroup.ADVERTISING),
  AD_TARGETING("Ad Targeting", IndustryGroup.ADVERTISING),
  ADVERTISING("Advertising", IndustryGroup.ADVERTISING),
  ADVERTISING_PLATFORMS("Advertising Platforms", IndustryGroup.ADVERTISING),
  AFFILIATE_MARKETING("Affiliate Marketing", IndustryGroup.ADVERTISING),
  LOCAL_ADVERTISING("Local Advertising", IndustryGroup.ADVERTISING),
  MOBILE_ADVERTISING("Mobile Advertising", IndustryGroup.ADVERTISING),
  OUTDOOR_ADVERTISING("Outdoor Advertising", IndustryGroup.ADVERTISING),
  SEM("SEM", IndustryGroup.ADVERTISING),
  SOCIAL_MEDIA_ADVERTISING("Social Media Advertising", IndustryGroup.ADVERTISING),
  VIDEO_ADVERTISING("Video Advertising", IndustryGroup.ADVERTISING),
  AGRICULTURE("Agriculture", IndustryGroup.AGRICULTURE_AND_FARMING),
  AGTECH("AgTech", IndustryGroup.AGRICULTURE_AND_FARMING),
  ANIMAL_FEED("Animal Feed", IndustryGroup.AGRICULTURE_AND_FARMING),
  AQUACULTURE("Aquaculture", IndustryGroup.AGRICULTURE_AND_FARMING),
  EQUESTRIAN("Equestrian", IndustryGroup.AGRICULTURE_AND_FARMING),
  FARMING("Farming", IndustryGroup.AGRICULTURE_AND_FARMING),
  FORESTRY("Forestry", IndustryGroup.AGRICULTURE_AND_FARMING),
  HORTICULTURE("Horticulture", IndustryGroup.AGRICULTURE_AND_FARMING),
  HYDROPONICS("Hydroponics", IndustryGroup.AGRICULTURE_AND_FARMING),
  LIVESTOCK("Livestock", IndustryGroup.AGRICULTURE_AND_FARMING),
  APP_DISCOVERY("App Discovery", IndustryGroup.APPS),
  APPS("Apps", IndustryGroup.APPS),
  CONSUMER_APPLICATIONS("Consumer Applications", IndustryGroup.APPS),
  ENTERPRISE_APPLICATIONS("Enterprise Applications", IndustryGroup.APPS),
  MOBILE_APPS("Mobile Apps", IndustryGroup.APPS),
  READING_APPS("Reading Apps", IndustryGroup.APPS),
  WEB_APPS("Web Apps", IndustryGroup.APPS),
  ARTIFICIAL_INTELLIGENCE("Artificial Intelligence", IndustryGroup.ARTIFICIAL_INTELLIGENCE),
  INTELLIGENT_SYSTEMS("Intelligent Systems", IndustryGroup.ARTIFICIAL_INTELLIGENCE),
  MACHINE_LEARNING("Machine Learning", IndustryGroup.ARTIFICIAL_INTELLIGENCE),
  PREDICTIVE_ANALYTICS_AI("Predictive Analytics", IndustryGroup.ARTIFICIAL_INTELLIGENCE),
  NATURAL_LANGUAGE_PROCESSING("Natural Language Processing", IndustryGroup.ARTIFICIAL_INTELLIGENCE),
  BIOINFORMATICS("Bioinformatics", IndustryGroup.BIOTECHNOLOGY),
  BIOMETRICS("Biometrics", IndustryGroup.BIOTECHNOLOGY),
  BIOPHARMA("Biopharma", IndustryGroup.BIOTECHNOLOGY),
  BIOTECHNOLOGY("Biotechnology", IndustryGroup.BIOTECHNOLOGY),
  GENETICS("Genetics", IndustryGroup.BIOTECHNOLOGY),
  LIFE_SCIENCE("Life Science", IndustryGroup.BIOTECHNOLOGY),
  NEUROSCIENCE("Neuroscience", IndustryGroup.BIOTECHNOLOGY),
  QUANTIFIED_SELF("Quantified Self", IndustryGroup.BIOTECHNOLOGY),
  FASHION("Fashion", IndustryGroup.CLOTHING_AND_APPAREL),
  LAUNDRY_AND_DRY_CLEANING("Laundry and Dry-cleaning", IndustryGroup.CLOTHING_AND_APPAREL),
  LINGERIE("Lingerie", IndustryGroup.CLOTHING_AND_APPAREL),
  SHOES("Shoes", IndustryGroup.CLOTHING_AND_APPAREL),
  AUCTIONS("Auctions", IndustryGroup.COMMERCE_AND_SHOPPING),
  CLASSIFIEDS("Classifieds", IndustryGroup.COMMERCE_AND_SHOPPING),
  COLLECTIBLES("Collectibles", IndustryGroup.COMMERCE_AND_SHOPPING),
  CONSUMER_REVIEWS("Consumer Reviews", IndustryGroup.COMMERCE_AND_SHOPPING),
  COUPONS("Coupons", IndustryGroup.COMMERCE_AND_SHOPPING),
  E_COMMERCE("E-Commerce", IndustryGroup.COMMERCE_AND_SHOPPING),
  E_COMMERCE_PLATFORMS("E-Commerce Platforms", IndustryGroup.COMMERCE_AND_SHOPPING),
  FLASH_SALE("Flash Sale", IndustryGroup.COMMERCE_AND_SHOPPING),
  GIFT("Gift", IndustryGroup.COMMERCE_AND_SHOPPING),
  GIFT_CARD("Gift Card", IndustryGroup.COMMERCE_AND_SHOPPING),
  GIFT_EXCHANGE("Gift Exchange", IndustryGroup.COMMERCE_AND_SHOPPING),
  GIFT_REGISTRY("Gift Registry", IndustryGroup.COMMERCE_AND_SHOPPING),
  GROUP_BUYING("Group Buying", IndustryGroup.COMMERCE_AND_SHOPPING),
  LOCAL_SHOPPING("Local Shopping", IndustryGroup.COMMERCE_AND_SHOPPING),
  MADE_TO_ORDER("Made to Order", IndustryGroup.COMMERCE_AND_SHOPPING),
  MARKETPLACE("Marketplace", IndustryGroup.COMMERCE_AND_SHOPPING),
  ONLINE_AUCTIONS("Online Auctions", IndustryGroup.COMMERCE_AND_SHOPPING),
  PERSONALIZATION("Personalization", IndustryGroup.COMMERCE_AND_SHOPPING),
  POINT_OF_SALE("Point of Sale", IndustryGroup.COMMERCE_AND_SHOPPING),
  PRICE_COMPARISON("Price Comparison", IndustryGroup.COMMERCE_AND_SHOPPING),
  RENTAL("Rental", IndustryGroup.COMMERCE_AND_SHOPPING),
  RETAIL("Retail", IndustryGroup.COMMERCE_AND_SHOPPING),
  RETAIL_TECHNOLOGY("Retail Technology", IndustryGroup.COMMERCE_AND_SHOPPING),
  SHOPPING("Shopping", IndustryGroup.COMMERCE_AND_SHOPPING),
  SHOPPING_MALL("Shopping Mall", IndustryGroup.COMMERCE_AND_SHOPPING),
  SOCIAL_SHOPPING("Social Shopping", IndustryGroup.COMMERCE_AND_SHOPPING),
  SPORTING_GOODS("Sporting Goods", IndustryGroup.COMMERCE_AND_SHOPPING),
  VENDING_AND_CONCESSIONS("Vending and Concessions", IndustryGroup.COMMERCE_AND_SHOPPING),
  VIRTUAL_GOODS("Virtual Goods", IndustryGroup.COMMERCE_AND_SHOPPING),
  WHOLESALE("Wholesale", IndustryGroup.COMMERCE_AND_SHOPPING),
  ADULT("Adult", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  BABY("Baby", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  CANNABIS("Cannabis", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  CHILDREN("Children", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  COMMUNITIES("Communities", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  DATING("Dating", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  ELDERLY("Elderly", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  FAMILY("Family", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  FUNERALS("Funerals", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  HUMANITARIAN("Humanitarian", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  LEISURE("Leisure", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  LGBT("LGBT", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  LIFESTYLE("Lifestyle", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  MENS("Men's", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  ONLINE_FORUMS("Online Forums", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  PARENTING("Parenting", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  PET("Pet", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  PRIVATE_SOCIAL_NETWORKING("Private Social Networking", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  PROFESSIONAL_NETWORKING("Professional Networking", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  QA("Q&A", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  RELIGION("Religion", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  RETIREMENT("Retirement", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  SEX_INDUSTRY("Sex Industry", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  SEX_TECH("Sex Tech", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  SOCIAL("Social", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  SOCIAL_ENTREPRENEURSHIP("Social Entrepreneurship", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  TEENAGERS("Teenagers", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  VIRTUAL_WORLD("Virtual World", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  WEDDING("Wedding", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  WOMENS("Women's", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  YOUNG_ADULTS("Young Adults", IndustryGroup.COMMUNITY_AND_LIFESTYLE),
  COMPUTER("Computer", IndustryGroup.CONSUMER_ELECTRONICS),
  CONSUMER_ELECTRONICS("Consumer Electronics", IndustryGroup.CONSUMER_ELECTRONICS),
  DRONES("Drones", IndustryGroup.CONSUMER_ELECTRONICS),
  ELECTRONICS("Electronics", IndustryGroup.CONSUMER_ELECTRONICS),
  GOOGLE_GLASS("Google Glass", IndustryGroup.CONSUMER_ELECTRONICS),
  MOBILE_DEVICES("Mobile Devices", IndustryGroup.CONSUMER_ELECTRONICS),
  NINTENDO("Nintendo", IndustryGroup.CONSUMER_ELECTRONICS),
  PLAYSTATION("Playstation", IndustryGroup.CONSUMER_ELECTRONICS),
  ROKU("Roku", IndustryGroup.CONSUMER_ELECTRONICS),
  SMART_HOME("Smart Home", IndustryGroup.CONSUMER_ELECTRONICS),
  WEARABLES("Wearables", IndustryGroup.CONSUMER_ELECTRONICS),
  WINDOWS_PHONE("Windows Phone", IndustryGroup.CONSUMER_ELECTRONICS),
  XBOX("Xbox", IndustryGroup.CONSUMER_ELECTRONICS),
  BEAUTY("Beauty", IndustryGroup.CONSUMER_GOODS),
  COMICS("Comics", IndustryGroup.CONSUMER_GOODS),
  CONSUMER_GOODS("Consumer Goods", IndustryGroup.CONSUMER_GOODS),
  COSMETICS("Cosmetics", IndustryGroup.CONSUMER_GOODS),
  DIY("DIY", IndustryGroup.CONSUMER_GOODS),
  DRONES_GOODS("Drones", IndustryGroup.CONSUMER_GOODS),
  EYEWEAR("Eyewear", IndustryGroup.CONSUMER_GOODS),
  FAST_MOVING_CONSUMER_GOODS("Fast-Moving Consumer Goods", IndustryGroup.CONSUMER_GOODS),
  FLOWERS("Flowers", IndustryGroup.CONSUMER_GOODS),
  FURNITURE("Furniture", IndustryGroup.CONSUMER_GOODS),
  GREEN_CONSUMER_GOODS("Green Consumer Goods", IndustryGroup.CONSUMER_GOODS),
  HANDMADE("Handmade", IndustryGroup.CONSUMER_GOODS),
  JEWELRY("Jewelry", IndustryGroup.CONSUMER_GOODS),
  LINGERIE_GOODS("Lingerie", IndustryGroup.CONSUMER_GOODS),
  SHOES_GOODS("Shoes", IndustryGroup.CONSUMER_GOODS),
  TOBACCO("Tobacco", IndustryGroup.CONSUMER_GOODS),
  TOYS("Toys", IndustryGroup.CONSUMER_GOODS),
  BLOGGING_PLATFORMS("Blogging Platforms", IndustryGroup.CONTENT_AND_PUBLISHING),
  CONTENT_DELIVERY_NETWORK("Content Delivery Network", IndustryGroup.CONTENT_AND_PUBLISHING),
  CONTENT_DISCOVERY("Content Discovery", IndustryGroup.CONTENT_AND_PUBLISHING),
  CONTENT_SYNDICATION("Content Syndication", IndustryGroup.CONTENT_AND_PUBLISHING),
  CREATIVE_AGENCY("Creative Agency", IndustryGroup.CONTENT_AND_PUBLISHING),
  DRM("DRM", IndustryGroup.CONTENT_AND_PUBLISHING),
  EBOOKS("EBooks", IndustryGroup.CONTENT_AND_PUBLISHING),
  JOURNALISM("Journalism", IndustryGroup.CONTENT_AND_PUBLISHING),
  NEWS("News", IndustryGroup.CONTENT_AND_PUBLISHING),
  PHOTO_EDITING("Photo Editing", IndustryGroup.CONTENT_AND_PUBLISHING),
  PHOTO_SHARING("Photo Sharing", IndustryGroup.CONTENT_AND_PUBLISHING),
  PHOTOGRAPHY("Photography", IndustryGroup.CONTENT_AND_PUBLISHING),
  PRINTING("Printing", IndustryGroup.CONTENT_AND_PUBLISHING),
  PUBLISHING("Publishing", IndustryGroup.CONTENT_AND_PUBLISHING),
  SOCIAL_BOOKMARKING("Social Bookmarking", IndustryGroup.CONTENT_AND_PUBLISHING),
  VIDEO_EDITING("Video Editing", IndustryGroup.CONTENT_AND_PUBLISHING),
  VIDEO_STREAMING("Video Streaming", IndustryGroup.CONTENT_AND_PUBLISHING),
  AB_TESTING("A/B Testing", IndustryGroup.DATA_AND_ANALYTICS),
  ANALYTICS("Analytics", IndustryGroup.DATA_AND_ANALYTICS),
  APPLICATION_PERFORMANCE_MANAGEMENT("Application Performance Management", IndustryGroup.DATA_AND_ANALYTICS),
  ARTIFICIAL_INTELLIGENCE_DATA("Artificial Intelligence", IndustryGroup.DATA_AND_ANALYTICS),
  BIG_DATA("Big Data", IndustryGroup.DATA_AND_ANALYTICS),
  BIOINFORMATICS_DATA("Bioinformatics", IndustryGroup.DATA_AND_ANALYTICS),
  BIOMETRICS_DATA("Biometrics", IndustryGroup.DATA_AND_ANALYTICS),
  BUSINESS_INTELLIGENCE("Business Intelligence", IndustryGroup.DATA_AND_ANALYTICS),
  CONSUMER_RESEARCH("Consumer Research", IndustryGroup.DATA_AND_ANALYTICS),
  DATA_INTEGRATION("Data Integration", IndustryGroup.DATA_AND_ANALYTICS),
  DATA_MINING("Data Mining", IndustryGroup.DATA_AND_ANALYTICS),
  DATA_VISUALIZATION("Data Visualization", IndustryGroup.DATA_AND_ANALYTICS),
  DATABASE("Database", IndustryGroup.DATA_AND_ANALYTICS),
  FACIAL_RECOGNITION("Facial Recognition", IndustryGroup.DATA_AND_ANALYTICS),
  GEOSPATIAL("Geospatial", IndustryGroup.DATA_AND_ANALYTICS),
  IMAGE_RECOGNITION("Image Recognition", IndustryGroup.DATA_AND_ANALYTICS),
  INTELLIGENT_SYSTEMS_DATA("Intelligent Systems", IndustryGroup.DATA_AND_ANALYTICS),
  LOCATION_BASED_SERVICES("Location Based Services", IndustryGroup.DATA_AND_ANALYTICS),
  MACHINE_LEARNING_DATA("Machine Learning", IndustryGroup.DATA_AND_ANALYTICS),
  MARKET_RESEARCH("Market Research", IndustryGroup.DATA_AND_ANALYTICS),
  NATURAL_LANGUAGE_PROCESSING_DATA("Natural Language Processing", IndustryGroup.ARTIFICIAL_INTELLIGENCE),
  PREDICTIVE_ANALYTICS("Predictive Analytics", IndustryGroup.DATA_AND_ANALYTICS),
  PRODUCT_RESEARCH("Product Research", IndustryGroup.DATA_AND_ANALYTICS),
  QUANTIFIED_SELF_DATA("Quantified Self", IndustryGroup.DATA_AND_ANALYTICS),
  SPEECH_RECOGNITION("Speech Recognition", IndustryGroup.DATA_AND_ANALYTICS),
  TEST_AND_MEASUREMENT("Test and Measurement", IndustryGroup.DATA_AND_ANALYTICS),
  TEXT_ANALYTICS("Text Analytics", IndustryGroup.DATA_AND_ANALYTICS),
  USABILITY_TESTING("Usability Testing", IndustryGroup.DATA_AND_ANALYTICS),
  CAD("CAD", IndustryGroup.DESIGN),
  CONSUMER_RESEARCH_DESIGN("Consumer Research", IndustryGroup.DESIGN),
  DATA_VISUALIZATION_DESIGN("Data Visualization", IndustryGroup.DESIGN),
  FASHION_DESIGN("Fashion", IndustryGroup.DESIGN),
  GRAPHIC_DESIGN("Graphic Design", IndustryGroup.DESIGN),
  HUMAN_COMPUTER_INTERACTION("Human Computer Interaction", IndustryGroup.DESIGN),
  INDUSTRIAL_DESIGN("Industrial Design", IndustryGroup.DESIGN),
  INTERIOR_DESIGN("Interior Design", IndustryGroup.DESIGN),
  MARKET_RESEARCH_DESIGN("Market Research", IndustryGroup.DESIGN),
  MECHANICAL_DESIGN("Mechanical Design", IndustryGroup.DESIGN),
  PRODUCT_DESIGN("Product Design", IndustryGroup.DESIGN),
  PRODUCT_RESEARCH_DESIGN("Product Research", IndustryGroup.DESIGN),
  USABILITY_TESTING_DESIGN("Usability Testing", IndustryGroup.DESIGN),
  UX_DESIGN("UX Design", IndustryGroup.DESIGN),
  WEB_DESIGN("Web Design", IndustryGroup.DESIGN),
  ALUMNI("Alumni", IndustryGroup.EDUCATION),
  CHARTER_SCHOOLS("Charter Schools", IndustryGroup.EDUCATION),
  COLLEGE_RECRUITING_EDUCATION("College Recruiting", IndustryGroup.EDUCATION),
  CONTINUING_EDUCATION("Continuing Education", IndustryGroup.EDUCATION),
  CORPORATE_TRAINING("Corporate Training", IndustryGroup.EDUCATION),
  E_LEARNING("E-Learning", IndustryGroup.EDUCATION),
  EDTECH("EdTech", IndustryGroup.EDUCATION),
  EDUCATION("Education", IndustryGroup.EDUCATION),
  EDUTAINMENT("Edutainment", IndustryGroup.EDUCATION),
  HIGHER_EDUCATION("Higher Education", IndustryGroup.EDUCATION),
  LANGUAGE_LEARNING("Language Learning", IndustryGroup.EDUCATION),
  MOOC("MOOC", IndustryGroup.EDUCATION),
  MUSIC_EDUCATION("Music Education", IndustryGroup.EDUCATION),
  PERSONAL_DEVELOPMENT("Personal Development", IndustryGroup.EDUCATION),
  PRIMARY_EDUCATION("Primary Education", IndustryGroup.EDUCATION),
  SECONDARY_EDUCATION("Secondary Education", IndustryGroup.EDUCATION),
  SKILL_ASSESSMENT("Skill Assessment", IndustryGroup.EDUCATION),
  STEM_EDUCATION("STEM Education", IndustryGroup.EDUCATION),
  TEXTBOOK("Textbook", IndustryGroup.EDUCATION),
  TRAINING("Training", IndustryGroup.EDUCATION),
  TUTORING("Tutoring", IndustryGroup.EDUCATION),
  VOCATIONAL_EDUCATION("Vocational Education", IndustryGroup.EDUCATION),
  BATTERY("Battery", IndustryGroup.ENERGY),
  BIOFUEL("Biofuel", IndustryGroup.ENERGY),
  BIOMASS_ENERGY("Biomass Energy", IndustryGroup.ENERGY),
  CLEAN_ENERGY("Clean Energy", IndustryGroup.ENERGY),
  ELECTRICAL_DISTRIBUTION("Electrical Distribution", IndustryGroup.ENERGY),
  ENERGY("Energy", IndustryGroup.ENERGY),
  ENERGY_EFFICIENCY("Energy Efficiency", IndustryGroup.ENERGY),
  ENERGY_MANAGEMENT("Energy Management", IndustryGroup.ENERGY),
  ENERGY_STORAGE("Energy Storage", IndustryGroup.ENERGY),
  FOSSIL_FUELS("Fossil Fuels", IndustryGroup.ENERGY),
  FUEL("Fuel", IndustryGroup.ENERGY),
  FUEL_CELL("Fuel Cell", IndustryGroup.ENERGY),
  OIL_AND_GAS("Oil and Gas", IndustryGroup.ENERGY),
  POWER_GRID("Power Grid", IndustryGroup.ENERGY),
  RENEWABLE_ENERGY("Renewable Energy", IndustryGroup.ENERGY),
  SOLAR("Solar", IndustryGroup.ENERGY),
  WIND_ENERGY("Wind Energy", IndustryGroup.ENERGY),
  CONCERTS("Concerts", IndustryGroup.EVENTS),
  EVENT_MANAGEMENT("Event Management", IndustryGroup.EVENTS),
  EVENT_PROMOTION("Event Promotion", IndustryGroup.EVENTS),
  EVENTS("Events", IndustryGroup.EVENTS),
  NIGHTCLUBS("Nightclubs", IndustryGroup.EVENTS),
  NIGHTLIFE("Nightlife", IndustryGroup.EVENTS),
  RESERVATIONS("Reservations", IndustryGroup.EVENTS),
  TICKETING("Ticketing", IndustryGroup.EVENTS),
  WEDDING_EVENTS("Wedding", IndustryGroup.EVENTS),
  ACCOUNTING("Accounting", IndustryGroup.FINANCIAL_SERVICES),
  ANGEL_INVESTMENT("Angel Investment", IndustryGroup.FINANCIAL_SERVICES),
  ASSET_MANAGEMENT("Asset Management", IndustryGroup.FINANCIAL_SERVICES),
  AUTO_INSURANCE("Auto Insurance", IndustryGroup.FINANCIAL_SERVICES),
  BANKING("Banking", IndustryGroup.FINANCIAL_SERVICES),
  BITCOIN("Bitcoin", IndustryGroup.FINANCIAL_SERVICES),
  COMMERCIAL_INSURANCE("Commercial Insurance", IndustryGroup.FINANCIAL_SERVICES),
  COMMERCIAL_LENDING("Commercial Lending", IndustryGroup.FINANCIAL_SERVICES),
  CONSUMER_LENDING("Consumer Lending", IndustryGroup.FINANCIAL_SERVICES),
  CREDIT("Credit", IndustryGroup.FINANCIAL_SERVICES),
  CREDIT_BUREAU("Credit Bureau", IndustryGroup.FINANCIAL_SERVICES),
  CREDIT_CARDS("Credit Cards", IndustryGroup.FINANCIAL_SERVICES),
  CROWDFUNDING("Crowdfunding", IndustryGroup.FINANCIAL_SERVICES),
  CRYPTOCURRENCY("Cryptocurrency", IndustryGroup.FINANCIAL_SERVICES),
  DEBIT_CARDS("Debit Cards", IndustryGroup.FINANCIAL_SERVICES),
  DEBT_COLLECTIONS_FINANCE("Debt Collections", IndustryGroup.FINANCIAL_SERVICES),
  FINANCE("Finance", IndustryGroup.FINANCIAL_SERVICES),
  FINANCIAL_EXCHANGES("Financial Exchanges", IndustryGroup.FINANCIAL_SERVICES),
  FINANCIAL_SERVICES("Financial Services", IndustryGroup.FINANCIAL_SERVICES),
  FINTECH("FinTech", IndustryGroup.FINANCIAL_SERVICES),
  FRAUD_DETECTION("Fraud Detection", IndustryGroup.FINANCIAL_SERVICES),
  FUNDING_PLATFORM("Funding Platform", IndustryGroup.FINANCIAL_SERVICES),
  GIFT_CARD_FINANCE("Gift Card", IndustryGroup.FINANCIAL_SERVICES),
  HEALTH_INSURANCE("Health Insurance", IndustryGroup.FINANCIAL_SERVICES),
  HEDGE_FUNDS("Hedge Funds", IndustryGroup.FINANCIAL_SERVICES),
  IMPACT_INVESTING("Impact Investing", IndustryGroup.FINANCIAL_SERVICES),
  INCUBATORS("Incubators", IndustryGroup.FINANCIAL_SERVICES),
  INSURANCE("Insurance", IndustryGroup.FINANCIAL_SERVICES),
  INSURTECH("InsurTech", IndustryGroup.FINANCIAL_SERVICES),
  LEASING("Leasing", IndustryGroup.FINANCIAL_SERVICES),
  LENDING("Lending", IndustryGroup.FINANCIAL_SERVICES),
  LIFE_INSURANCE("Life Insurance", IndustryGroup.FINANCIAL_SERVICES),
  MICRO_LENDING("Micro Lending", IndustryGroup.FINANCIAL_SERVICES),
  MOBILE_PAYMENTS("Mobile Payments", IndustryGroup.FINANCIAL_SERVICES),
  PAYMENTS("Payments", IndustryGroup.FINANCIAL_SERVICES),
  PERSONAL_FINANCE("Personal Finance", IndustryGroup.FINANCIAL_SERVICES),
  PREDICTION_MARKETS("Prediction Markets", IndustryGroup.FINANCIAL_SERVICES),
  PROPERTY_INSURANCE("Property Insurance", IndustryGroup.FINANCIAL_SERVICES),
  REAL_ESTATE_INVESTMENT("Real Estate Investment", IndustryGroup.FINANCIAL_SERVICES),
  STOCK_EXCHANGES("Stock Exchanges", IndustryGroup.FINANCIAL_SERVICES),
  TRADING_PLATFORM("Trading Platform", IndustryGroup.FINANCIAL_SERVICES),
  TRANSACTION_PROCESSING("Transaction Processing", IndustryGroup.FINANCIAL_SERVICES),
  VENTURE_CAPITAL("Venture Capital", IndustryGroup.FINANCIAL_SERVICES),
  VIRTUAL_CURRENCY("Virtual Currency", IndustryGroup.FINANCIAL_SERVICES),
  WEALTH_MANAGEMENT("Wealth Management", IndustryGroup.FINANCIAL_SERVICES),
  BAKERY("Bakery", IndustryGroup.FOOD_AND_BEVERAGE),
  BREWING("Brewing", IndustryGroup.FOOD_AND_BEVERAGE),
  CANNABIS_FOOD("Cannabis", IndustryGroup.FOOD_AND_BEVERAGE),
  CATERING("Catering", IndustryGroup.FOOD_AND_BEVERAGE),
  COFFEE("Coffee", IndustryGroup.FOOD_AND_BEVERAGE),
  CONFECTIONERY("Confectionery", IndustryGroup.FOOD_AND_BEVERAGE),
  COOKING("Cooking", IndustryGroup.FOOD_AND_BEVERAGE),
  CRAFT_BEER("Craft Beer", IndustryGroup.FOOD_AND_BEVERAGE),
  DIETARY_SUPPLEMENTS("Dietary Supplements", IndustryGroup.FOOD_AND_BEVERAGE),
  DISTILLERY("Distillery", IndustryGroup.FOOD_AND_BEVERAGE),
  FARMERS_MARKET("Farmers Market", IndustryGroup.FOOD_AND_BEVERAGE),
  FOOD_AND_BEVERAGE("Food and Beverage", IndustryGroup.FOOD_AND_BEVERAGE),
  FOOD_DELIVERY("Food Delivery", IndustryGroup.FOOD_AND_BEVERAGE),
  FOOD_PROCESSING("Food Processing", IndustryGroup.FOOD_AND_BEVERAGE),
  FOOD_TRUCKS("Food Trucks", IndustryGroup.FOOD_AND_BEVERAGE),
  FRUIT("Fruit", IndustryGroup.FOOD_AND_BEVERAGE),
  GROCERY("Grocery", IndustryGroup.FOOD_AND_BEVERAGE),
  NUTRITION("Nutrition", IndustryGroup.FOOD_AND_BEVERAGE),
  ORGANIC_FOOD("Organic Food", IndustryGroup.FOOD_AND_BEVERAGE),
  RECIPES("Recipes", IndustryGroup.FOOD_AND_BEVERAGE),
  RESTAURANTS("Restaurants", IndustryGroup.FOOD_AND_BEVERAGE),
  SEAFOOD("Seafood", IndustryGroup.FOOD_AND_BEVERAGE),
  SNACK_FOOD("Snack Food", IndustryGroup.FOOD_AND_BEVERAGE),
  TEA("Tea", IndustryGroup.FOOD_AND_BEVERAGE),
  TOBACCO_FOOD("Tobacco", IndustryGroup.FOOD_AND_BEVERAGE),
  WINE_AND_SPIRITS("Wine And Spirits", IndustryGroup.FOOD_AND_BEVERAGE),
  WINERY("Winery", IndustryGroup.FOOD_AND_BEVERAGE),
  CASUAL_GAMES("Casual Games", IndustryGroup.GAMING),
  CONSOLE_GAMES("Console Games", IndustryGroup.GAMING),
  CONTESTS("Contests", IndustryGroup.GAMING),
  FANTASY_SPORTS("Fantasy Sports", IndustryGroup.GAMING),
  GAMBLING("Gambling", IndustryGroup.GAMING),
  GAMIFICATION("Gamification", IndustryGroup.GAMING),
  GAMING("Gaming", IndustryGroup.GAMING),
  MMO_GAMES("MMO Games", IndustryGroup.GAMING),
  ONLINE_GAMES("Online Games", IndustryGroup.GAMING),
  PC_GAMES("PC Games", IndustryGroup.GAMING),
  SERIOUS_GAMES("Serious Games", IndustryGroup.GAMING),
  VIDEO_GAMES("Video Games", IndustryGroup.GAMING),
  CIVICTECH("CivicTech", IndustryGroup.GOVERNMENT_AND_MILITARY),
  GOVERNMENT("Government", IndustryGroup.GOVERNMENT_AND_MILITARY),
  GOVTECH("GovTech", IndustryGroup.GOVERNMENT_AND_MILITARY),
  LAW_ENFORCEMENT("Law Enforcement", IndustryGroup.GOVERNMENT_AND_MILITARY),
  MILITARY("Military", IndustryGroup.GOVERNMENT_AND_MILITARY),
  NATIONAL_SECURITY("National Security", IndustryGroup.GOVERNMENT_AND_MILITARY),
  POLITICS("Politics", IndustryGroup.GOVERNMENT_AND_MILITARY),
  PUBLIC_SAFETY("Public Safety", IndustryGroup.GOVERNMENT_AND_MILITARY),
  SOCIAL_ASSISTANCE("Social Assistance", IndustryGroup.GOVERNMENT_AND_MILITARY),
  THREE_D_TECHNOLOGY("3D Technology", IndustryGroup.HARDWARE),
  APPLICATION_SPECIFIC_INTEGRATED_CIRCUIT("Application Specific Integrated Circuit (ASIC)", IndustryGroup.HARDWARE),
  AUGMENTED_REALITY("Augmented Reality", IndustryGroup.HARDWARE),
  CLOUD_INFRASTRUCTURE("Cloud Infrastructure", IndustryGroup.HARDWARE),
  COMMUNICATION_HARDWARE("Communication Hardware", IndustryGroup.HARDWARE),
  COMMUNICATIONS_INFRASTRUCTURE("Communications Infrastructure", IndustryGroup.HARDWARE),
  COMPUTER_HARDWARE("Computer", IndustryGroup.HARDWARE),
  COMPUTER_VISION("Computer Vision", IndustryGroup.HARDWARE),
  CONSUMER_ELECTRONICS_HARDWARE("Consumer Electronics", IndustryGroup.HARDWARE),
  DATA_CENTER("Data Center", IndustryGroup.HARDWARE),
  DATA_CENTER_AUTOMATION("Data Center Automation", IndustryGroup.HARDWARE),
  DATA_STORAGE("Data Storage", IndustryGroup.HARDWARE),
  DRONE_MANAGEMENT("Drone Management", IndustryGroup.HARDWARE),
  DRONES_HARDWARE("Drones", IndustryGroup.HARDWARE),
  DSP("DSP", IndustryGroup.HARDWARE),
  ELECTRONIC_DESIGN_AUTOMATION("Electronic Design Automation (EDA)", IndustryGroup.HARDWARE),
  ELECTRONICS_HARDWARE("Electronics", IndustryGroup.HARDWARE),
  EMBEDDED_SYSTEMS("Embedded Systems", IndustryGroup.HARDWARE),
  FIELD_PROGRAMMABLE_GATE_ARRAY("Field-Programmable Gate Array (FPGA)", IndustryGroup.HARDWARE),
  FLASH_STORAGE("Flash Storage", IndustryGroup.HARDWARE),
  GOOGLE_GLASS_HARDWARE("Google Glass", IndustryGroup.HARDWARE),
  GPS("GPS", IndustryGroup.HARDWARE),
  GPU("GPU", IndustryGroup.HARDWARE),
  HARDWARE("Hardware", IndustryGroup.HARDWARE),
  INDUSTRIAL_DESIGN_HARDWARE("Industrial Design", IndustryGroup.HARDWARE),
  LASER("Laser", IndustryGroup.HARDWARE),
  LIGHTING("Lighting", IndustryGroup.HARDWARE),
  MECHANICAL_DESIGN_HARDWARE("Mechanical Design", IndustryGroup.HARDWARE),
  MOBILE_DEVICES_HARDWARE("Mobile Devices", IndustryGroup.HARDWARE),
  NETWORK_HARDWARE("Network Hardware", IndustryGroup.HARDWARE),
  NFC("NFC", IndustryGroup.HARDWARE),
  NINTENDO_HARDWARE("Nintendo", IndustryGroup.HARDWARE),
  OPTICAL_COMMUNICATION("Optical Communication", IndustryGroup.HARDWARE),
  PLAYSTATION_HARDWARE("Playstation", IndustryGroup.HARDWARE),
  PRIVATE_CLOUD("Private Cloud", IndustryGroup.HARDWARE),
  RETAIL_TECHNOLOGY_HARDWARE("Retail Technology", IndustryGroup.HARDWARE),
  RFID("RFID", IndustryGroup.HARDWARE),
  RISC("RISC", IndustryGroup.HARDWARE),
  ROBOTICS("Robotics", IndustryGroup.HARDWARE),
  ROKU_HARDWARE("Roku", IndustryGroup.HARDWARE),
  SATELLITE_COMMUNICATION("Satellite Communication", IndustryGroup.HARDWARE),
  SEMICONDUCTOR("Semiconductor", IndustryGroup.HARDWARE),
  SENSOR("Sensor", IndustryGroup.HARDWARE),
  SEX_TECH_HARDWARE("Sex Tech", IndustryGroup.HARDWARE),
  TELECOMMUNICATIONS("Telecommunications", IndustryGroup.HARDWARE),
  VIDEO_CONFERENCING("Video Conferencing", IndustryGroup.HARDWARE),
  VIRTUAL_REALITY("Virtual Reality", IndustryGroup.HARDWARE),
  VIRTUALIZATION("Virtualization", IndustryGroup.HARDWARE),
  WEARABLES_HARDWARE("Wearables", IndustryGroup.HARDWARE),
  WINDOWS_PHONE_HARDWARE("Windows Phone", IndustryGroup.HARDWARE),
  WIRELESS("Wireless", IndustryGroup.HARDWARE),
  XBOX_HARDWARE("Xbox", IndustryGroup.HARDWARE),
  ALTERNATIVE_MEDICINE("Alternative Medicine", IndustryGroup.HEALTH_CARE),
  ASSISTED_LIVING("Assisted Living", IndustryGroup.HEALTH_CARE),
  ASSISTIVE_TECHNOLOGY("Assistive Technology", IndustryGroup.HEALTH_CARE),
  BIOPHARMA_HEALTH("Biopharma", IndustryGroup.HEALTH_CARE),
  CANNABIS_HEALTH("Cannabis", IndustryGroup.HEALTH_CARE),
  CHILD_CARE("Child Care", IndustryGroup.HEALTH_CARE),
  CLINICAL_TRIALS("Clinical Trials", IndustryGroup.HEALTH_CARE),
  COSMETIC_SURGERY("Cosmetic Surgery", IndustryGroup.HEALTH_CARE),
  DENTAL("Dental", IndustryGroup.HEALTH_CARE),
  DIABETES("Diabetes", IndustryGroup.HEALTH_CARE),
  DIETARY_SUPPLEMENTS_HEALTH("Dietary Supplements", IndustryGroup.HEALTH_CARE),
  ELDER_CARE("Elder Care", IndustryGroup.HEALTH_CARE),
  ELECTRONIC_HEALTH_RECORD("Electronic Health Record (EHR)", IndustryGroup.HEALTH_CARE),
  EMERGENCY_MEDICINE("Emergency Medicine", IndustryGroup.HEALTH_CARE),
  EMPLOYEE_BENEFITS_HEALTH("Employee Benefits", IndustryGroup.HEALTH_CARE),
  FERTILITY("Fertility", IndustryGroup.HEALTH_CARE),
  FIRST_AID("First Aid", IndustryGroup.HEALTH_CARE),
  FUNERALS_HEALTH("Funerals", IndustryGroup.HEALTH_CARE),
  GENETICS_HEALTH("Genetics", IndustryGroup.HEALTH_CARE),
  HEALTH_CARE("Health Care", IndustryGroup.HEALTH_CARE),
  HEALTH_DIAGNOSTICS("Health Diagnostics", IndustryGroup.HEALTH_CARE),
  HOME_HEALTH_CARE("Home Health Care", IndustryGroup.HEALTH_CARE),
  HOSPITAL("Hospital", IndustryGroup.HEALTH_CARE),
  MEDICAL("Medical", IndustryGroup.HEALTH_CARE),
  MEDICAL_DEVICE("Medical Device", IndustryGroup.HEALTH_CARE),
  MHEALTH("mHealth", IndustryGroup.HEALTH_CARE),
  NURSING_AND_RESIDENTIAL_CARE("Nursing and Residential Care", IndustryGroup.HEALTH_CARE),
  NUTRACEUTICAL("Nutraceutical", IndustryGroup.HEALTH_CARE),
  NUTRITION_HEALTH("Nutrition", IndustryGroup.HEALTH_CARE),
  OUTPATIENT_CARE("Outpatient Care", IndustryGroup.HEALTH_CARE),
  PERSONAL_HEALTH("Personal Health", IndustryGroup.HEALTH_CARE),
  PHARMACEUTICAL("Pharmaceutical", IndustryGroup.HEALTH_CARE),
  PSYCHOLOGY("Psychology", IndustryGroup.HEALTH_CARE),
  REHABILITATION("Rehabilitation", IndustryGroup.HEALTH_CARE),
  THERAPEUTICS("Therapeutics", IndustryGroup.HEALTH_CARE),
  VETERINARY("Veterinary", IndustryGroup.HEALTH_CARE),
  WELLNESS("Wellness", IndustryGroup.HEALTH_CARE),
  BUSINESS_INFORMATION_SYSTEMS("Business Information Systems", IndustryGroup.INFORMATION_TECHNOLOGY),
  CIVICTECH_IT("CivicTech", IndustryGroup.INFORMATION_TECHNOLOGY),
  CLOUD_DATA_SERVICES("Cloud Data Services", IndustryGroup.INFORMATION_TECHNOLOGY),
  CLOUD_MANAGEMENT("Cloud Management", IndustryGroup.INFORMATION_TECHNOLOGY),
  CLOUD_SECURITY("Cloud Security", IndustryGroup.INFORMATION_TECHNOLOGY),
  CMS("CMS", IndustryGroup.INFORMATION_TECHNOLOGY),
  CONTACT_MANAGEMENT("Contact Management", IndustryGroup.INFORMATION_TECHNOLOGY),
  CRM("CRM", IndustryGroup.INFORMATION_TECHNOLOGY),
  CYBER_SECURITY("Cyber Security", IndustryGroup.INFORMATION_TECHNOLOGY),
  DATA_CENTER_IT("Data Center", IndustryGroup.INFORMATION_TECHNOLOGY),
  DATA_CENTER_AUTOMATION_IT("Data Center Automation", IndustryGroup.INFORMATION_TECHNOLOGY),
  DATA_INTEGRATION_IT("Data Integration", IndustryGroup.INFORMATION_TECHNOLOGY),
  DATA_MINING_IT("Data Mining", IndustryGroup.INFORMATION_TECHNOLOGY),
  DATA_VISUALIZATION_IT("Data Visualization", IndustryGroup.INFORMATION_TECHNOLOGY),
  DOCUMENT_MANAGEMENT("Document Management", IndustryGroup.INFORMATION_TECHNOLOGY),
  E_SIGNATURE("E-Signature", IndustryGroup.INFORMATION_TECHNOLOGY),
  EMAIL("Email", IndustryGroup.INFORMATION_TECHNOLOGY),
  GOVTECH_IT("GovTech", IndustryGroup.INFORMATION_TECHNOLOGY),
  IDENTITY_MANAGEMENT("Identity Management", IndustryGroup.INFORMATION_TECHNOLOGY),
  INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY(
    "Information and Communications Technology (ICT)",
    IndustryGroup.INFORMATION_TECHNOLOGY
  ),
  INFORMATION_SERVICES("Information Services", IndustryGroup.INFORMATION_TECHNOLOGY),
  INFORMATION_TECHNOLOGY("Information Technology", IndustryGroup.INFORMATION_TECHNOLOGY),
  INTRUSION_DETECTION("Intrusion Detection", IndustryGroup.INFORMATION_TECHNOLOGY),
  IT_INFRASTRUCTURE("IT Infrastructure", IndustryGroup.INFORMATION_TECHNOLOGY),
  IT_MANAGEMENT("IT Management", IndustryGroup.INFORMATION_TECHNOLOGY),
  MANAGEMENT_INFORMATION_SYSTEMS("Management Information Systems", IndustryGroup.INFORMATION_TECHNOLOGY),
  MESSAGING("Messaging", IndustryGroup.INFORMATION_TECHNOLOGY),
  MILITARY_IT("Military", IndustryGroup.INFORMATION_TECHNOLOGY),
  NETWORK_SECURITY("Network Security", IndustryGroup.INFORMATION_TECHNOLOGY),
  PENETRATION_TESTING("Penetration Testing", IndustryGroup.INFORMATION_TECHNOLOGY),
  PRIVATE_CLOUD_IT("Private Cloud", IndustryGroup.INFORMATION_TECHNOLOGY),
  REPUTATION("Reputation", IndustryGroup.INFORMATION_TECHNOLOGY),
  SALES_AUTOMATION("Sales Automation", IndustryGroup.INFORMATION_TECHNOLOGY),
  SCHEDULING("Scheduling", IndustryGroup.INFORMATION_TECHNOLOGY),
  SOCIAL_CRM("Social CRM", IndustryGroup.INFORMATION_TECHNOLOGY),
  SPAM_FILTERING("Spam Filtering", IndustryGroup.INFORMATION_TECHNOLOGY),
  TECHNICAL_SUPPORT("Technical Support", IndustryGroup.INFORMATION_TECHNOLOGY),
  UNIFIED_COMMUNICATIONS("Unified Communications", IndustryGroup.INFORMATION_TECHNOLOGY),
  VIDEO_CHAT("Video Chat", IndustryGroup.INFORMATION_TECHNOLOGY),
  VIDEO_CONFERENCING_IT("Video Conferencing", IndustryGroup.INFORMATION_TECHNOLOGY),
  VIRTUALIZATION_IT("Virtualization", IndustryGroup.INFORMATION_TECHNOLOGY),
  VOIP("VoIP", IndustryGroup.INFORMATION_TECHNOLOGY),
  CLOUD_COMPUTING("Cloud Computing", IndustryGroup.INTERNET_SERVICES),
  CLOUD_DATA_SERVICES_INTERNET("Cloud Data Services", IndustryGroup.INTERNET_SERVICES),
  CLOUD_INFRASTRUCTURE_INTERNET("Cloud Infrastructure", IndustryGroup.INTERNET_SERVICES),
  CLOUD_MANAGEMENT_INTERNET("Cloud Management", IndustryGroup.INTERNET_SERVICES),
  CLOUD_STORAGE("Cloud Storage", IndustryGroup.INTERNET_SERVICES),
  DARKNET("Darknet", IndustryGroup.INTERNET_SERVICES),
  DOMAIN_REGISTRAR("Domain Registrar", IndustryGroup.INTERNET_SERVICES),
  E_COMMERCE_PLATFORMS_INTERNET("E-Commerce Platforms", IndustryGroup.INTERNET_SERVICES),
  EDISCOVERY("Ediscovery", IndustryGroup.INTERNET_SERVICES),
  EMAIL_INTERNET("Email", IndustryGroup.INTERNET_SERVICES),
  INTERNET("Internet", IndustryGroup.INTERNET_SERVICES),
  INTERNET_OF_THINGS("Internet of Things", IndustryGroup.INTERNET_SERVICES),
  ISP("ISP", IndustryGroup.INTERNET_SERVICES),
  LOCATION_BASED_SERVICES_INTERNET("Location Based Services", IndustryGroup.INTERNET_SERVICES),
  MESSAGING_INTERNET("Messaging", IndustryGroup.INTERNET_SERVICES),
  MUSIC_STREAMING("Music Streaming", IndustryGroup.INTERNET_SERVICES),
  ONLINE_FORUMS_INTERNET("Online Forums", IndustryGroup.INTERNET_SERVICES),
  ONLINE_PORTALS("Online Portals", IndustryGroup.INTERNET_SERVICES),
  PRIVATE_CLOUD_INTERNET("Private Cloud", IndustryGroup.INTERNET_SERVICES),
  PRODUCT_SEARCH("Product Search", IndustryGroup.INTERNET_SERVICES),
  SEARCH_ENGINE("Search Engine", IndustryGroup.INTERNET_SERVICES),
  SEM_INTERNET("SEM", IndustryGroup.INTERNET_SERVICES),
  SEMANTIC_SEARCH("Semantic Search", IndustryGroup.INTERNET_SERVICES),
  SEMANTIC_WEB("Semantic Web", IndustryGroup.INTERNET_SERVICES),
  SEO("SEO", IndustryGroup.INTERNET_SERVICES),
  SMS("SMS", IndustryGroup.INTERNET_SERVICES),
  SOCIAL_MEDIA("Social Media", IndustryGroup.INTERNET_SERVICES),
  SOCIAL_MEDIA_MANAGEMENT("Social Media Management", IndustryGroup.INTERNET_SERVICES),
  SOCIAL_NETWORK("Social Network", IndustryGroup.INTERNET_SERVICES),
  UNIFIED_COMMUNICATIONS_INTERNET("Unified Communications", IndustryGroup.INTERNET_SERVICES),
  VERTICAL_SEARCH("Vertical Search", IndustryGroup.INTERNET_SERVICES),
  VIDEO_CHAT_INTERNET("Video Chat", IndustryGroup.INTERNET_SERVICES),
  VIDEO_CONFERENCING_INTERNET("Video Conferencing", IndustryGroup.INTERNET_SERVICES),
  VISUAL_SEARCH("Visual Search", IndustryGroup.INTERNET_SERVICES),
  VOIP_INTERNET("VoIP", IndustryGroup.INTERNET_SERVICES),
  WEB_BROWSERS("Web Browsers", IndustryGroup.INTERNET_SERVICES),
  WEB_HOSTING("Web Hosting", IndustryGroup.INTERNET_SERVICES),
  ANGEL_INVESTMENT_INVESTMENTS("Angel Investment", IndustryGroup.LENDING_AND_INVESTMENTS),
  BANKING_INVESTMENTS("Banking", IndustryGroup.LENDING_AND_INVESTMENTS),
  COMMERCIAL_LENDING_INVESTMENTS("Commercial Lending", IndustryGroup.LENDING_AND_INVESTMENTS),
  CONSUMER_LENDING_INVESTMENTS("Consumer Lending", IndustryGroup.LENDING_AND_INVESTMENTS),
  CREDIT_INVESTMENTS("Credit", IndustryGroup.LENDING_AND_INVESTMENTS),
  CREDIT_CARDS_INVESTMENTS("Credit Cards", IndustryGroup.LENDING_AND_INVESTMENTS),
  FINANCIAL_EXCHANGES_INVESTMENTS("Financial Exchanges", IndustryGroup.LENDING_AND_INVESTMENTS),
  FUNDING_PLATFORM_INVESTMENTS("Funding Platform", IndustryGroup.LENDING_AND_INVESTMENTS),
  HEDGE_FUNDS_INVESTMENTS("Hedge Funds", IndustryGroup.LENDING_AND_INVESTMENTS),
  IMPACT_INVESTING_INVESTMENTS("Impact Investing", IndustryGroup.LENDING_AND_INVESTMENTS),
  INCUBATORS_INVESTMENTS("Incubators", IndustryGroup.LENDING_AND_INVESTMENTS),
  MICRO_LENDING_INVESTMENTS("Micro Lending", IndustryGroup.LENDING_AND_INVESTMENTS),
  STOCK_EXCHANGES_INVESTMENTS("Stock Exchanges", IndustryGroup.LENDING_AND_INVESTMENTS),
  TRADING_PLATFORM_INVESTMENTS("Trading Platform", IndustryGroup.LENDING_AND_INVESTMENTS),
  VENTURE_CAPITAL_INVESTMENTS("Venture Capital", IndustryGroup.LENDING_AND_INVESTMENTS),
  THREE_D_PRINTING("3D Printing", IndustryGroup.MANUFACTURING),
  ADVANCED_MATERIALS("Advanced Materials", IndustryGroup.MANUFACTURING),
  FOUNDRIES("Foundries", IndustryGroup.MANUFACTURING),
  INDUSTRIAL("Industrial", IndustryGroup.MANUFACTURING),
  INDUSTRIAL_AUTOMATION("Industrial Automation", IndustryGroup.MANUFACTURING),
  INDUSTRIAL_ENGINEERING("Industrial Engineering", IndustryGroup.MANUFACTURING),
  INDUSTRIAL_MANUFACTURING("Industrial Manufacturing", IndustryGroup.MANUFACTURING),
  MACHINERY_MANUFACTURING("Machinery Manufacturing", IndustryGroup.MANUFACTURING),
  MANUFACTURING("Manufacturing", IndustryGroup.MANUFACTURING),
  PAPER_MANUFACTURING("Paper Manufacturing", IndustryGroup.MANUFACTURING),
  PLASTICS_AND_RUBBER_MANUFACTURING("Plastics and Rubber Manufacturing", IndustryGroup.MANUFACTURING),
  TEXTILES("Textiles", IndustryGroup.MANUFACTURING),
  WOOD_PROCESSING("Wood Processing", IndustryGroup.MANUFACTURING),
  ADVICE("Advice", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  ANIMATION("Animation", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  ART("Art", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  AUDIO("Audio", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  AUDIOBOOKS("Audiobooks", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  BLOGGING_PLATFORMS_MEDIA("Blogging Platforms", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  BROADCASTING("Broadcasting", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  CELEBRITY("Celebrity", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  CONCERTS_MEDIA("Concerts", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  CONTENT("Content", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  CONTENT_CREATORS("Content Creators", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  CONTENT_DISCOVERY_MEDIA("Content Discovery", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  CONTENT_SYNDICATION_MEDIA("Content Syndication", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  CREATIVE_AGENCY_MEDIA("Creative Agency", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  DIGITAL_ENTERTAINMENT("Digital Entertainment", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  DIGITAL_MEDIA("Digital Media", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  DRM_MEDIA("DRM", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  EBOOKS_MEDIA("EBooks", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  EDUTAINMENT_MEDIA("Edutainment", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  EVENT_MANAGEMENT_MEDIA("Event Management", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  EVENT_PROMOTION_MEDIA("Event Promotion", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  EVENTS_MEDIA("Events", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  FILM("Film", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  FILM_DISTRIBUTION("Film Distribution", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  FILM_PRODUCTION("Film Production", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  GUIDES("Guides", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  IN_FLIGHT_ENTERTAINMENT("In-Flight Entertainment", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  INDEPENDENT_MUSIC("Independent Music", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  INTERNET_RADIO("Internet Radio", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  JOURNALISM_MEDIA("Journalism", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  MEDIA_AND_ENTERTAINMENT("Media and Entertainment", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  MOTION_CAPTURE("Motion Capture", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  MUSIC("Music", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  MUSIC_EDUCATION_MEDIA("Music Education", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  MUSIC_LABEL("Music Label", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  MUSIC_STREAMING_MEDIA("Music Streaming", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  MUSIC_VENUES("Music Venues", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  MUSICAL_INSTRUMENTS("Musical Instruments", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  NEWS_MEDIA("News", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  NIGHTCLUBS_MEDIA("Nightclubs", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  NIGHTLIFE_MEDIA("Nightlife", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  PERFORMING_ARTS("Performing Arts", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  PHOTO_EDITING_MEDIA("Photo Editing", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  PHOTO_SHARING_MEDIA("Photo Sharing", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  PHOTOGRAPHY_MEDIA("Photography", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  PODCAST("Podcast", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  PRINTING_MEDIA("Printing", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  PUBLISHING_MEDIA("Publishing", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  RESERVATIONS_MEDIA("Reservations", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  SOCIAL_MEDIA_MEDIA("Social Media", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  SOCIAL_NEWS("Social News", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  THEATRE("Theatre", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  TICKETING_MEDIA("Ticketing", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  TV("TV", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  TV_PRODUCTION("TV Production", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  VIDEO("Video", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  VIDEO_EDITING_MEDIA("Video Editing", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  VIDEO_ON_DEMAND("Video on Demand", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  VIDEO_STREAMING_MEDIA("Video Streaming", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  VIRTUAL_WORLD_MEDIA("Virtual World", IndustryGroup.MEDIA_AND_ENTERTAINMENT),
  EMAIL_MEDIA("Email", IndustryGroup.MESSAGING_AND_TELECOMMUNICATIONS),
  MEETING_SOFTWARE("Meeting Software", IndustryGroup.MESSAGING_AND_TELECOMMUNICATIONS),
  MESSAGING_MEDIA("Messaging", IndustryGroup.MESSAGING_AND_TELECOMMUNICATIONS),
  SMS_MEDIA("SMS", IndustryGroup.MESSAGING_AND_TELECOMMUNICATIONS),
  UNIFIED_COMMUNICATIONS_MEDIA("Unified Communications", IndustryGroup.MESSAGING_AND_TELECOMMUNICATIONS),
  VIDEO_CHAT_MEDIA("Video Chat", IndustryGroup.MESSAGING_AND_TELECOMMUNICATIONS),
  VIDEO_CONFERENCING_MEDIA("Video Conferencing", IndustryGroup.MESSAGING_AND_TELECOMMUNICATIONS),
  VOIP_MEDIA("VoIP", IndustryGroup.MESSAGING_AND_TELECOMMUNICATIONS),
  WIRED_TELECOMMUNICATIONS("Wired Telecommunications", IndustryGroup.MESSAGING_AND_TELECOMMUNICATIONS),
  ANDROID("Android", IndustryGroup.MOBILE),
  GOOGLE_GLASS_MOBILE("Google Glass", IndustryGroup.MOBILE),
  IOS("iOS", IndustryGroup.MOBILE),
  MHEALTH_MOBILE("mHealth", IndustryGroup.MOBILE),
  MOBILE("Mobile", IndustryGroup.MOBILE),
  MOBILE_APPS_MOBILE("Mobile Apps", IndustryGroup.MOBILE),
  MOBILE_DEVICES_MOBILE("Mobile Devices", IndustryGroup.MOBILE),
  MOBILE_PAYMENTS_MOBILE("Mobile Payments", IndustryGroup.MOBILE),
  WINDOWS_PHONE_MOBILE("Windows Phone", IndustryGroup.MOBILE),
  WIRELESS_MOBILE("Wireless", IndustryGroup.MOBILE),
  AUDIO_AUDIO("Audio", IndustryGroup.MUSIC_AND_AUDIO),
  AUDIOBOOKS_AUDIO("Audiobooks", IndustryGroup.MUSIC_AND_AUDIO),
  INDEPENDENT_MUSIC_AUDIO("Independent Music", IndustryGroup.MUSIC_AND_AUDIO),
  INTERNET_RADIO_AUDIO("Internet Radio", IndustryGroup.MUSIC_AND_AUDIO),
  MUSIC_AUDIO("Music", IndustryGroup.MUSIC_AND_AUDIO),
  MUSIC_EDUCATION_AUDIO("Music Education", IndustryGroup.MUSIC_AND_AUDIO),
  MUSIC_LABEL_AUDIO("Music Label", IndustryGroup.MUSIC_AND_AUDIO),
  MUSIC_STREAMING_AUDIO("Music Streaming", IndustryGroup.MUSIC_AND_AUDIO),
  MUSICAL_INSTRUMENTS_AUDIO("Musical Instruments", IndustryGroup.MUSIC_AND_AUDIO),
  PODCAST_AUDIO("Podcast", IndustryGroup.MUSIC_AND_AUDIO),
  BIOFUEL_RESOURCES("Biofuel", IndustryGroup.NATURAL_RESOURCES),
  BIOMASS_ENERGY_RESOURCES("Biomass Energy", IndustryGroup.NATURAL_RESOURCES),
  FOSSIL_FUELS_RESOURCES("Fossil Fuels", IndustryGroup.NATURAL_RESOURCES),
  MINERAL("Mineral", IndustryGroup.NATURAL_RESOURCES),
  MINING("Mining", IndustryGroup.NATURAL_RESOURCES),
  MINING_TECHNOLOGY("Mining Technology", IndustryGroup.NATURAL_RESOURCES),
  NATURAL_RESOURCES("Natural Resources", IndustryGroup.NATURAL_RESOURCES),
  OIL_AND_GAS_RESOURCES("Oil and Gas", IndustryGroup.NATURAL_RESOURCES),
  PRECIOUS_METALS("Precious Metals", IndustryGroup.NATURAL_RESOURCES),
  SOLAR_RESOURCES("Solar", IndustryGroup.NATURAL_RESOURCES),
  TIMBER("Timber", IndustryGroup.NATURAL_RESOURCES),
  WATER("Water", IndustryGroup.NATURAL_RESOURCES),
  WIND_ENERGY_RESOURCES("Wind Energy", IndustryGroup.NATURAL_RESOURCES),
  GEOSPATIAL_NAVIGATION("Geospatial", IndustryGroup.NAVIGATION_AND_MAPPING),
  GPS_NAVIGATION("GPS", IndustryGroup.NAVIGATION_AND_MAPPING),
  INDOOR_POSITIONING("Indoor Positioning", IndustryGroup.NAVIGATION_AND_MAPPING),
  LOCATION_BASED_SERVICES_NAVIGATION("Location Based Services", IndustryGroup.NAVIGATION_AND_MAPPING),
  MAPPING_SERVICES("Mapping Services", IndustryGroup.NAVIGATION_AND_MAPPING),
  NAVIGATION("Navigation", IndustryGroup.NAVIGATION_AND_MAPPING),
  ALUMNI_OTHER("Alumni", IndustryGroup.OTHER),
  ASSOCIATION("Association", IndustryGroup.OTHER),
  B2B("B2B", IndustryGroup.OTHER),
  B2C("B2C", IndustryGroup.OTHER),
  BLOCKCHAIN("Blockchain", IndustryGroup.OTHER),
  CHARITY("Charity", IndustryGroup.OTHER),
  COLLABORATION("Collaboration", IndustryGroup.OTHER),
  COLLABORATIVE_CONSUMPTION("Collaborative Consumption", IndustryGroup.OTHER),
  COMMERCIAL("Commercial", IndustryGroup.OTHER),
  CONSUMER("Consumer", IndustryGroup.OTHER),
  CROWDSOURCING("Crowdsourcing", IndustryGroup.OTHER),
  CUSTOMER_SERVICE("Customer Service", IndustryGroup.OTHER),
  DESKTOP_APPS("Desktop Apps", IndustryGroup.OTHER),
  EMERGING_MARKETS("Emerging Markets", IndustryGroup.OTHER),
  ENTERPRISE("Enterprise", IndustryGroup.OTHER),
  ETHEREUM("Ethereum", IndustryGroup.OTHER),
  FRANCHISE("Franchise", IndustryGroup.OTHER),
  FREEMIUM("Freemium", IndustryGroup.OTHER),
  GENERATION_Y("Generation Y", IndustryGroup.OTHER),
  GENERATION_Z("Generation Z", IndustryGroup.OTHER),
  HOMELESS_SHELTER("Homeless Shelter", IndustryGroup.OTHER),
  INFRASTRUCTURE("Infrastructure", IndustryGroup.OTHER),
  KNOWLEDGE_MANAGEMENT_OTHER("Knowledge Management", IndustryGroup.OTHER),
  LGBT_MILLENNIALS("LGBT Millennials", IndustryGroup.OTHER),
  NON_PROFIT("Non Profit", IndustryGroup.OTHER),
  PEER_TO_PEER("Peer to Peer", IndustryGroup.OTHER),
  PROFESSIONAL_SERVICES("Professional Services", IndustryGroup.OTHER),
  PROJECT_MANAGEMENT_OTHER("Project Management", IndustryGroup.OTHER),
  REAL_TIME("Real Time", IndustryGroup.OTHER),
  RETIREMENT_OTHER("Retirement", IndustryGroup.OTHER),
  SERVICE_INDUSTRY("Service Industry", IndustryGroup.OTHER),
  SHARING_ECONOMY("Sharing Economy", IndustryGroup.OTHER),
  SMALL_AND_MEDIUM_BUSINESSES("Small and Medium Businesses", IndustryGroup.OTHER),
  SOCIAL_BOOKMARKING_OTHER("Social Bookmarking", IndustryGroup.OTHER),
  SOCIAL_IMPACT("Social Impact", IndustryGroup.OTHER),
  SUBSCRIPTION_SERVICE("Subscription Service", IndustryGroup.OTHER),
  TECHNICAL_SUPPORT_OTHER("Technical Support", IndustryGroup.OTHER),
  UNDERSERVED_CHILDREN("Underserved Children", IndustryGroup.OTHER),
  UNIVERSITIES("Universities", IndustryGroup.OTHER),
  BILLING("Billing", IndustryGroup.PAYMENTS),
  BITCOIN_PAYMENTS("Bitcoin", IndustryGroup.PAYMENTS),
  CREDIT_CARDS_PAYMENTS("Credit Cards", IndustryGroup.PAYMENTS),
  CRYPTOCURRENCY_PAYMENTS("Cryptocurrency", IndustryGroup.PAYMENTS),
  DEBIT_CARDS_PAYMENTS("Debit Cards", IndustryGroup.PAYMENTS),
  FRAUD_DETECTION_PAYMENTS("Fraud Detection", IndustryGroup.PAYMENTS),
  MOBILE_PAYMENTS_PAYMENTS("Mobile Payments", IndustryGroup.PAYMENTS),
  PAYMENTS_PAYMENTS("Payments", IndustryGroup.PAYMENTS),
  TRANSACTION_PROCESSING_PAYMENTS("Transaction Processing", IndustryGroup.PAYMENTS),
  VIRTUAL_CURRENCY_PAYMENTS("Virtual Currency", IndustryGroup.PAYMENTS),
  ANDROID_PLATFORMS("Android", IndustryGroup.PLATFORMS),
  FACEBOOK("Facebook", IndustryGroup.PLATFORMS),
  GOOGLE("Google", IndustryGroup.PLATFORMS),
  GOOGLE_GLASS_PLATFORMS("Google Glass", IndustryGroup.PLATFORMS),
  IOS_PLATFORMS("iOS", IndustryGroup.PLATFORMS),
  LINUX("Linux", IndustryGroup.PLATFORMS),
  MACOS("macOS", IndustryGroup.PLATFORMS),
  NINTENDO_PLATFORMS("Nintendo", IndustryGroup.PLATFORMS),
  OPERATING_SYSTEMS("Operating Systems", IndustryGroup.PLATFORMS),
  PLAYSTATION_PLATFORMS("Playstation", IndustryGroup.PLATFORMS),
  ROKU_PLATFORMS("Roku", IndustryGroup.PLATFORMS),
  TIZEN("Tizen", IndustryGroup.PLATFORMS),
  TWITTER("Twitter", IndustryGroup.PLATFORMS),
  WEBOS("WebOS", IndustryGroup.PLATFORMS),
  WINDOWS("Windows", IndustryGroup.PLATFORMS),
  WINDOWS_PHONE_PLATFORMS("Windows Phone", IndustryGroup.PLATFORMS),
  XBOX_PLATFORMS("Xbox", IndustryGroup.PLATFORMS),
  CLOUD_SECURITY_PRIVACY("Cloud Security", IndustryGroup.PRIVACY_AND_SECURITY),
  CORRECTIONS_FACILITIES("Corrections Facilities", IndustryGroup.PRIVACY_AND_SECURITY),
  CYBER_SECURITY_PRIVACY("Cyber Security", IndustryGroup.PRIVACY_AND_SECURITY),
  DRM_PRIVACY("DRM", IndustryGroup.PRIVACY_AND_SECURITY),
  E_SIGNATURE_PRIVACY("E-Signature", IndustryGroup.PRIVACY_AND_SECURITY),
  FRAUD_DETECTION_PRIVACY("Fraud Detection", IndustryGroup.PRIVACY_AND_SECURITY),
  HOMELAND_SECURITY_PRIVACY("Homeland Security", IndustryGroup.PRIVACY_AND_SECURITY),
  IDENTITY_MANAGEMENT_PRIVACY("Identity Management", IndustryGroup.PRIVACY_AND_SECURITY),
  INTRUSION_DETECTION_PRIVACY("Intrusion Detection", IndustryGroup.PRIVACY_AND_SECURITY),
  LAW_ENFORCEMENT_PRIVACY("Law Enforcement", IndustryGroup.PRIVACY_AND_SECURITY),
  NETWORK_SECURITY_PRIVACY("Network Security", IndustryGroup.PRIVACY_AND_SECURITY),
  PENETRATION_TESTING_PRIVACY("Penetration Testing", IndustryGroup.PRIVACY_AND_SECURITY),
  PHYSICAL_SECURITY_PRIVACY("Physical Security", IndustryGroup.PRIVACY_AND_SECURITY),
  PRIVACY("Privacy", IndustryGroup.PRIVACY_AND_SECURITY),
  SECURITY("Security", IndustryGroup.PRIVACY_AND_SECURITY),
  ACCOUNTING_PROFESSIONAL("Accounting", IndustryGroup.PROFESSIONAL_SERVICES),
  BUSINESS_DEVELOPMENT("Business Development", IndustryGroup.PROFESSIONAL_SERVICES),
  CAREER_PLANNING("Career Planning", IndustryGroup.PROFESSIONAL_SERVICES),
  COMPLIANCE("Compliance", IndustryGroup.PROFESSIONAL_SERVICES),
  CONSULTING("Consulting", IndustryGroup.PROFESSIONAL_SERVICES),
  CUSTOMER_SERVICE_PROFESSIONAL("Customer Service", IndustryGroup.PROFESSIONAL_SERVICES),
  EMPLOYMENT("Employment", IndustryGroup.PROFESSIONAL_SERVICES),
  ENVIRONMENTAL_CONSULTING("Environmental Consulting", IndustryGroup.PROFESSIONAL_SERVICES),
  FIELD_SUPPORT("Field Support", IndustryGroup.PROFESSIONAL_SERVICES),
  FREELANCE("Freelance", IndustryGroup.PROFESSIONAL_SERVICES),
  INTELLECTUAL_PROPERTY("Intellectual Property", IndustryGroup.PROFESSIONAL_SERVICES),
  INNOVATION_MANAGEMENT("Innovation Management", IndustryGroup.PROFESSIONAL_SERVICES),
  LEGAL("Legal", IndustryGroup.PROFESSIONAL_SERVICES),
  LEGAL_TECH("Legal Tech", IndustryGroup.PROFESSIONAL_SERVICES),
  MANAGEMENT_CONSULTING("Management Consulting", IndustryGroup.PROFESSIONAL_SERVICES),
  OUTSOURCING("Outsourcing", IndustryGroup.PROFESSIONAL_SERVICES),
  PROFESSIONAL_NETWORKING_PROFESSIONAL("Professional Networking", IndustryGroup.PROFESSIONAL_SERVICES),
  QUALITY_ASSURANCE("Quality Assurance", IndustryGroup.PROFESSIONAL_SERVICES),
  RECRUITING("Recruiting", IndustryGroup.PROFESSIONAL_SERVICES),
  RISK_MANAGEMENT("Risk Management", IndustryGroup.PROFESSIONAL_SERVICES),
  SOCIAL_RECRUITING("Social Recruiting", IndustryGroup.PROFESSIONAL_SERVICES),
  TRANSLATION_SERVICE("Translation Service", IndustryGroup.PROFESSIONAL_SERVICES),
  ARCHITECTURE("Architecture", IndustryGroup.REAL_ESTATE),
  BUILDING_MAINTENANCE("Building Maintenance", IndustryGroup.REAL_ESTATE),
  BUILDING_MATERIAL("Building Material", IndustryGroup.REAL_ESTATE),
  COMMERCIAL_REAL_ESTATE("Commercial Real Estate", IndustryGroup.REAL_ESTATE),
  CONSTRUCTION("Construction", IndustryGroup.REAL_ESTATE),
  COWORKING("Coworking", IndustryGroup.REAL_ESTATE),
  FACILITY_MANAGEMENT("Facility Management", IndustryGroup.REAL_ESTATE),
  FAST_MOVING_CONSUMER_GOODS_REAL_ESTATE("Fast-Moving Consumer Goods", IndustryGroup.REAL_ESTATE),
  GREEN_BUILDING("Green Building", IndustryGroup.REAL_ESTATE),
  HOME_AND_GARDEN("Home and Garden", IndustryGroup.REAL_ESTATE),
  HOME_DECOR("Home Decor", IndustryGroup.REAL_ESTATE),
  HOME_IMPROVEMENT("Home Improvement", IndustryGroup.REAL_ESTATE),
  HOME_RENOVATION("Home Renovation", IndustryGroup.REAL_ESTATE),
  HOME_SERVICES("Home Services", IndustryGroup.REAL_ESTATE),
  INTERIOR_DESIGN_REAL_ESTATE("Interior Design", IndustryGroup.REAL_ESTATE),
  JANITORIAL_SERVICE("Janitorial Service", IndustryGroup.REAL_ESTATE),
  LANDSCAPING("Landscaping", IndustryGroup.REAL_ESTATE),
  PROPERTY_DEVELOPMENT("Property Development", IndustryGroup.REAL_ESTATE),
  PROPERTY_MANAGEMENT("Property Management", IndustryGroup.REAL_ESTATE),
  REAL_ESTATE("Real Estate", IndustryGroup.REAL_ESTATE),
  REAL_ESTATE_INVESTMENT_REAL_ESTATE("Real Estate Investment", IndustryGroup.REAL_ESTATE),
  RENTAL_PROPERTY("Rental Property", IndustryGroup.REAL_ESTATE),
  RESIDENTIAL("Residential", IndustryGroup.REAL_ESTATE),
  SELF_STORAGE("Self-Storage", IndustryGroup.REAL_ESTATE),
  SMART_BUILDING("Smart Building", IndustryGroup.REAL_ESTATE),
  SMART_CITIES("Smart Cities", IndustryGroup.REAL_ESTATE),
  SMART_HOME_REAL_ESTATE("Smart Home", IndustryGroup.REAL_ESTATE),
  TIMESHARE("Timeshare", IndustryGroup.REAL_ESTATE),
  VACATION_RENTAL("Vacation Rental", IndustryGroup.REAL_ESTATE),
  ADVERTISING_SALES("Advertising", IndustryGroup.SALES_AND_MARKETING),
  AFFILIATE_MARKETING_SALES("Affiliate Marketing", IndustryGroup.SALES_AND_MARKETING),
  APP_DISCOVERY_SALES("App Discovery", IndustryGroup.SALES_AND_MARKETING),
  APP_MARKETING("App Marketing", IndustryGroup.SALES_AND_MARKETING),
  BRAND_MARKETING("Brand Marketing", IndustryGroup.SALES_AND_MARKETING),
  CAUSE_MARKETING("Cause Marketing", IndustryGroup.SALES_AND_MARKETING),
  CONTENT_MARKETING("Content Marketing", IndustryGroup.SALES_AND_MARKETING),
  CRM_SALES("CRM", IndustryGroup.SALES_AND_MARKETING),
  DIGITAL_MARKETING("Digital Marketing", IndustryGroup.SALES_AND_MARKETING),
  DIGITAL_SIGNAGE("Digital Signage", IndustryGroup.SALES_AND_MARKETING),
  DIRECT_MARKETING("Direct Marketing", IndustryGroup.SALES_AND_MARKETING),
  DIRECT_SALES("Direct Sales", IndustryGroup.SALES_AND_MARKETING),
  EMAIL_MARKETING("Email Marketing", IndustryGroup.SALES_AND_MARKETING),
  LEAD_GENERATION("Lead Generation", IndustryGroup.SALES_AND_MARKETING),
  LEAD_MANAGEMENT("Lead Management", IndustryGroup.SALES_AND_MARKETING),
  LOCAL("Local", IndustryGroup.SALES_AND_MARKETING),
  LOCAL_ADVERTISING_SALES("Local Advertising", IndustryGroup.SALES_AND_MARKETING),
  LOCAL_BUSINESS("Local Business", IndustryGroup.SALES_AND_MARKETING),
  LOYALTY_PROGRAMS("Loyalty Programs", IndustryGroup.SALES_AND_MARKETING),
  MARKETING("Marketing", IndustryGroup.SALES_AND_MARKETING),
  MARKETING_AUTOMATION("Marketing Automation", IndustryGroup.SALES_AND_MARKETING),
  MOBILE_ADVERTISING_SALES("Mobile Advertising", IndustryGroup.SALES_AND_MARKETING),
  MULTI_LEVEL_MARKETING("Multi-level Marketing", IndustryGroup.SALES_AND_MARKETING),
  OUTDOOR_ADVERTISING_SALES("Outdoor Advertising", IndustryGroup.SALES_AND_MARKETING),
  PERSONAL_BRANDING("Personal Branding", IndustryGroup.SALES_AND_MARKETING),
  PUBLIC_RELATIONS("Public Relations", IndustryGroup.SALES_AND_MARKETING),
  SALES("Sales", IndustryGroup.SALES_AND_MARKETING),
  SALES_AUTOMATION_SALES("Sales Automation", IndustryGroup.SALES_AND_MARKETING),
  SEM_SALES("SEM", IndustryGroup.SALES_AND_MARKETING),
  SEO_SALES("SEO", IndustryGroup.SALES_AND_MARKETING),
  SOCIAL_CRM_SALES("Social CRM", IndustryGroup.SALES_AND_MARKETING),
  SOCIAL_MEDIA_ADVERTISING_SALES("Social Media Advertising", IndustryGroup.SALES_AND_MARKETING),
  SOCIAL_MEDIA_MANAGEMENT_SALES("Social Media Management", IndustryGroup.SALES_AND_MARKETING),
  SOCIAL_MEDIA_MARKETING("Social Media Marketing", IndustryGroup.SALES_AND_MARKETING),
  SPONSORSHIP("Sponsorship", IndustryGroup.SALES_AND_MARKETING),
  VIDEO_ADVERTISING_SALES("Video Advertising", IndustryGroup.SALES_AND_MARKETING),
  ADVANCED_MATERIALS_SCIENCE("Advanced Materials", IndustryGroup.SCIENCE_AND_ENGINEERING),
  AEROSPACE("Aerospace", IndustryGroup.SCIENCE_AND_ENGINEERING),
  ARTIFICIAL_INTELLIGENCE_SCIENCE("Artificial Intelligence", IndustryGroup.SCIENCE_AND_ENGINEERING),
  BIOINFORMATICS_SCIENCE("Bioinformatics", IndustryGroup.SCIENCE_AND_ENGINEERING),
  BIOMETRICS_SCIENCE("Biometrics", IndustryGroup.SCIENCE_AND_ENGINEERING),
  BIOPHARMA_SCIENCE("Biopharma", IndustryGroup.SCIENCE_AND_ENGINEERING),
  BIOTECHNOLOGY_SCIENCE("Biotechnology", IndustryGroup.SCIENCE_AND_ENGINEERING),
  CHEMICAL("Chemical", IndustryGroup.SCIENCE_AND_ENGINEERING),
  CHEMICAL_ENGINEERING("Chemical Engineering", IndustryGroup.SCIENCE_AND_ENGINEERING),
  CIVIL_ENGINEERING("Civil Engineering", IndustryGroup.SCIENCE_AND_ENGINEERING),
  EMBEDDED_SYSTEMS_SCIENCE("Embedded Systems", IndustryGroup.SCIENCE_AND_ENGINEERING),
  ENVIRONMENTAL_ENGINEERING("Environmental Engineering", IndustryGroup.SCIENCE_AND_ENGINEERING),
  HUMAN_COMPUTER_INTERACTION_SCIENCE("Human Computer Interaction", IndustryGroup.SCIENCE_AND_ENGINEERING),
  INDUSTRIAL_AUTOMATION_SCIENCE("Industrial Automation", IndustryGroup.SCIENCE_AND_ENGINEERING),
  INDUSTRIAL_ENGINEERING_SCIENCE("Industrial Engineering", IndustryGroup.SCIENCE_AND_ENGINEERING),
  INTELLIGENT_SYSTEMS_SCIENCE("Intelligent Systems", IndustryGroup.SCIENCE_AND_ENGINEERING),
  LASER_SCIENCE("Laser", IndustryGroup.SCIENCE_AND_ENGINEERING),
  LIFE_SCIENCE_SCIENCE("Life Science", IndustryGroup.SCIENCE_AND_ENGINEERING),
  MARINE_TECHNOLOGY("Marine Technology", IndustryGroup.SCIENCE_AND_ENGINEERING),
  MECHANICAL_ENGINEERING("Mechanical Engineering", IndustryGroup.SCIENCE_AND_ENGINEERING),
  NANOTECHNOLOGY("Nanotechnology", IndustryGroup.SCIENCE_AND_ENGINEERING),
  NEUROSCIENCE_SCIENCE("Neuroscience", IndustryGroup.SCIENCE_AND_ENGINEERING),
  NUCLEAR("Nuclear", IndustryGroup.SCIENCE_AND_ENGINEERING),
  QUANTUM_COMPUTING("Quantum Computing", IndustryGroup.SCIENCE_AND_ENGINEERING),
  ROBOTICS_SCIENCE("Robotics", IndustryGroup.SCIENCE_AND_ENGINEERING),
  SEMICONDUCTOR_SCIENCE("Semiconductor", IndustryGroup.SCIENCE_AND_ENGINEERING),
  SOFTWARE_ENGINEERING("Software Engineering", IndustryGroup.SCIENCE_AND_ENGINEERING),
  STEM_EDUCATION_SCIENCE("STEM Education", IndustryGroup.SCIENCE_AND_ENGINEERING),
  THREE_D_TECHNOLOGY_SOFTWARE("3D Technology", IndustryGroup.SOFTWARE),
  ANDROID_SOFTWARE("Android", IndustryGroup.SOFTWARE),
  APP_DISCOVERY_SOFTWARE("App Discovery", IndustryGroup.SOFTWARE),
  APPLICATION_PERFORMANCE_MANAGEMENT_SOFTWARE("Application Performance Management", IndustryGroup.SOFTWARE),
  APPS_SOFTWARE("Apps", IndustryGroup.SOFTWARE),
  ARTIFICIAL_INTELLIGENCE_SOFTWARE("Artificial Intelligence", IndustryGroup.SOFTWARE),
  AUGMENTED_REALITY_SOFTWARE("Augmented Reality", IndustryGroup.SOFTWARE),
  BILLING_SOFTWARE("Billing", IndustryGroup.SOFTWARE),
  BITCOIN_SOFTWARE("Bitcoin", IndustryGroup.SOFTWARE),
  BROWSER_EXTENSIONS("Browser Extensions", IndustryGroup.SOFTWARE),
  CAD_SOFTWARE("CAD", IndustryGroup.SOFTWARE),
  CLOUD_COMPUTING_SOFTWARE("Cloud Computing", IndustryGroup.SOFTWARE),
  CLOUD_MANAGEMENT_SOFTWARE("Cloud Management", IndustryGroup.SOFTWARE),
  CMS_SOFTWARE("CMS", IndustryGroup.SOFTWARE),
  COMPUTER_VISION_SOFTWARE("Computer Vision", IndustryGroup.SOFTWARE),
  CONSUMER_APPLICATIONS_SOFTWARE("Consumer Applications", IndustryGroup.SOFTWARE),
  CONSUMER_SOFTWARE("Consumer Software", IndustryGroup.SOFTWARE),
  CONTACT_MANAGEMENT_SOFTWARE("Contact Management", IndustryGroup.SOFTWARE),
  CRM_SOFTWARE("CRM", IndustryGroup.SOFTWARE),
  CRYPTOCURRENCY_SOFTWARE("Cryptocurrency", IndustryGroup.SOFTWARE),
  DATA_CENTER_AUTOMATION_SOFTWARE("Data Center Automation", IndustryGroup.SOFTWARE),
  DATA_INTEGRATION_SOFTWARE("Data Integration", IndustryGroup.SOFTWARE),
  DATA_STORAGE_SOFTWARE("Data Storage", IndustryGroup.SOFTWARE),
  DATA_VISUALIZATION_SOFTWARE("Data Visualization", IndustryGroup.SOFTWARE),
  DATABASE_SOFTWARE("Database", IndustryGroup.SOFTWARE),
  DEVELOPER_APIS("Developer APIs", IndustryGroup.SOFTWARE),
  DEVELOPER_PLATFORM("Developer Platform", IndustryGroup.SOFTWARE),
  DEVELOPER_TOOLS("Developer Tools", IndustryGroup.SOFTWARE),
  DOCUMENT_MANAGEMENT_SOFTWARE("Document Management", IndustryGroup.SOFTWARE),
  DRONE_MANAGEMENT_SOFTWARE("Drone Management", IndustryGroup.SOFTWARE),
  E_LEARNING_SOFTWARE("E-Learning", IndustryGroup.SOFTWARE),
  EDTECH_SOFTWARE("EdTech", IndustryGroup.SOFTWARE),
  ELECTRONIC_DESIGN_AUTOMATION_SOFTWARE("Electronic Design Automation (EDA)", IndustryGroup.SOFTWARE),
  EMBEDDED_SOFTWARE("Embedded Software", IndustryGroup.SOFTWARE),
  EMBEDDED_SYSTEMS_SOFTWARE("Embedded Systems", IndustryGroup.SOFTWARE),
  ENTERPRISE_APPLICATIONS_SOFTWARE("Enterprise Applications", IndustryGroup.SOFTWARE),
  ENTERPRISE_RESOURCE_PLANNING("Enterprise Resource Planning (ERP)", IndustryGroup.SOFTWARE),
  ENTERPRISE_SOFTWARE("Enterprise Software", IndustryGroup.SOFTWARE),
  FACIAL_RECOGNITION_SOFTWARE("Facial Recognition", IndustryGroup.SOFTWARE),
  FILE_SHARING("File Sharing", IndustryGroup.SOFTWARE),
  IAAS("IaaS", IndustryGroup.SOFTWARE),
  IMAGE_RECOGNITION_SOFTWARE("Image Recognition", IndustryGroup.SOFTWARE),
  IOS_SOFTWARE("iOS", IndustryGroup.SOFTWARE),
  LINUX_SOFTWARE("Linux", IndustryGroup.SOFTWARE),
  MACHINE_LEARNING_SOFTWARE("Machine Learning", IndustryGroup.SOFTWARE),
  MACOS_SOFTWARE("macOS", IndustryGroup.SOFTWARE),
  MARKETING_AUTOMATION_SOFTWARE("Marketing Automation", IndustryGroup.SOFTWARE),
  MEETING_SOFTWARE_SOFTWARE("Meeting Software", IndustryGroup.SOFTWARE),
  MOBILE_APPS_SOFTWARE("Mobile Apps", IndustryGroup.SOFTWARE),
  MOBILE_PAYMENTS_SOFTWARE("Mobile Payments", IndustryGroup.SOFTWARE),
  MOOC_SOFTWARE("MOOC", IndustryGroup.SOFTWARE),
  NATURAL_LANGUAGE_PROCESSING_SOFTWARE("Natural Language Processing", IndustryGroup.SOFTWARE),
  OPEN_SOURCE("Open Source", IndustryGroup.SOFTWARE),
  OPERATING_SYSTEMS_SOFTWARE("Operating Systems", IndustryGroup.SOFTWARE),
  PAAS("PaaS", IndustryGroup.SOFTWARE),
  PREDICTIVE_ANALYTICS_SOFTWARE("Predictive Analytics", IndustryGroup.SOFTWARE),
  PRESENTATION_SOFTWARE("Presentation Software", IndustryGroup.SOFTWARE),
  PRESENTATIONS("Presentations", IndustryGroup.SOFTWARE),
  PRIVATE_CLOUD_SOFTWARE("Private Cloud", IndustryGroup.SOFTWARE),
  PRODUCTIVITY_TOOLS("Productivity Tools", IndustryGroup.SOFTWARE),
  PRODUCT_MANAGEMENT_QR_CODES("Product Management QR Codes", IndustryGroup.SOFTWARE),
  READING_APPS_SOFTWARE("Reading Apps", IndustryGroup.SOFTWARE),
  RETAIL_TECHNOLOGY_SOFTWARE("Retail Technology", IndustryGroup.SOFTWARE),
  ROBOTICS_SOFTWARE("Robotics", IndustryGroup.SOFTWARE),
  SAAS("SaaS", IndustryGroup.SOFTWARE),
  SALES_AUTOMATION_SOFTWARE("Sales Automation", IndustryGroup.SOFTWARE),
  SCHEDULING_SOFTWARE("Scheduling", IndustryGroup.SOFTWARE),
  SEX_TECH_SOFTWARE("Sex Tech", IndustryGroup.SOFTWARE),
  SIMULATION("Simulation", IndustryGroup.SOFTWARE),
  SNS("SNS", IndustryGroup.SOFTWARE),
  SOCIAL_CRM_SOFTWARE("Social CRM", IndustryGroup.SOFTWARE),
  SOFTWARE("Software", IndustryGroup.SOFTWARE),
  SOFTWARE_ENGINEERING_SOFTWARE("Software Engineering", IndustryGroup.SOFTWARE),
  SPEECH_RECOGNITION_SOFTWARE("Speech Recognition", IndustryGroup.SOFTWARE),
  TASK_MANAGEMENT("Task Management", IndustryGroup.SOFTWARE),
  TEXT_ANALYTICS_SOFTWARE("Text Analytics", IndustryGroup.SOFTWARE),
  TRANSACTION_PROCESSING_SOFTWARE("Transaction Processing", IndustryGroup.SOFTWARE),
  VIDEO_CONFERENCING_SOFTWARE("Video Conferencing", IndustryGroup.SOFTWARE),
  VIRTUAL_ASSISTANT("Virtual Assistant", IndustryGroup.SOFTWARE),
  VIRTUAL_CURRENCY_SOFTWARE("Virtual Currency", IndustryGroup.SOFTWARE),
  VIRTUAL_DESKTOP("Virtual Desktop", IndustryGroup.SOFTWARE),
  VIRTUAL_GOODS_SOFTWARE("Virtual Goods", IndustryGroup.SOFTWARE),
  VIRTUAL_REALITY_SOFTWARE("Virtual Reality", IndustryGroup.SOFTWARE),
  VIRTUAL_WORLD_SOFTWARE("Virtual World", IndustryGroup.SOFTWARE),
  VIRTUALIZATION_SOFTWARE("Virtualization", IndustryGroup.SOFTWARE),
  WEB_APPS_SOFTWARE("Web Apps", IndustryGroup.SOFTWARE),
  WEB_BROWSERS_SOFTWARE("Web Browsers", IndustryGroup.SOFTWARE),
  WEB_DEVELOPMENT("Web Development", IndustryGroup.SOFTWARE),
  AMERICAN_FOOTBALL("American Football", IndustryGroup.SPORTS),
  BASEBALL("Baseball", IndustryGroup.SPORTS),
  BASKETBALL("Basketball", IndustryGroup.SPORTS),
  BOATING("Boating", IndustryGroup.SPORTS),
  CRICKET("Cricket", IndustryGroup.SPORTS),
  CYCLING("Cycling", IndustryGroup.SPORTS),
  DIVING("Diving", IndustryGroup.SPORTS),
  ESPORTS("eSports", IndustryGroup.SPORTS),
  FANTASY_SPORTS_SPORTS("Fantasy Sports", IndustryGroup.SPORTS),
  FITNESS("Fitness", IndustryGroup.SPORTS),
  GOLF("Golf", IndustryGroup.SPORTS),
  HOCKEY("Hockey", IndustryGroup.SPORTS),
  HUNTING("Hunting", IndustryGroup.SPORTS),
  OUTDOORS("Outdoors", IndustryGroup.SPORTS),
  RACING("Racing", IndustryGroup.SPORTS),
  RECREATION("Recreation", IndustryGroup.SPORTS),
  RUGBY("Rugby", IndustryGroup.SPORTS),
  SAILING("Sailing", IndustryGroup.SPORTS),
  SKIING("Skiing", IndustryGroup.SPORTS),
  SOCCER("Soccer", IndustryGroup.SPORTS),
  SPORTING_GOODS_SPORTS("Sporting Goods", IndustryGroup.SPORTS),
  SPORTS("Sports", IndustryGroup.SPORTS),
  SURFING("Surfing", IndustryGroup.SPORTS),
  SWIMMING("Swimming", IndustryGroup.SPORTS),
  TABLE_TENNIS("Table Tennis", IndustryGroup.SPORTS),
  TENNIS("Tennis", IndustryGroup.SPORTS),
  ULTIMATE_FRISBEE("Ultimate Frisbee", IndustryGroup.SPORTS),
  VOLLEY_BALL("Volley Ball", IndustryGroup.SPORTS),
  BIOFUEL_SUSTAINABILITY("Biofuel", IndustryGroup.SUSTAINABILITY),
  BIOMASS_ENERGY_SUSTAINABILITY("Biomass Energy", IndustryGroup.SUSTAINABILITY),
  CLEAN_ENERGY_SUSTAINABILITY("Clean Energy", IndustryGroup.SUSTAINABILITY),
  CLEANTECH("CleanTech", IndustryGroup.SUSTAINABILITY),
  ENERGY_EFFICIENCY_SUSTAINABILITY("Energy Efficiency", IndustryGroup.SUSTAINABILITY),
  ENVIRONMENTAL_ENGINEERING_SUSTAINABILITY("Environmental Engineering", IndustryGroup.SUSTAINABILITY),
  GREEN_BUILDING_SUSTAINABILITY("Green Building", IndustryGroup.SUSTAINABILITY),
  GREEN_CONSUMER_GOODS_SUSTAINABILITY("Green Consumer Goods", IndustryGroup.SUSTAINABILITY),
  GREENTECH("GreenTech", IndustryGroup.SUSTAINABILITY),
  NATURAL_RESOURCES_SUSTAINABILITY("Natural Resources", IndustryGroup.SUSTAINABILITY),
  ORGANIC("Organic", IndustryGroup.SUSTAINABILITY),
  POLLUTION_CONTROL("Pollution Control", IndustryGroup.SUSTAINABILITY),
  RECYCLING("Recycling", IndustryGroup.SUSTAINABILITY),
  RENEWABLE_ENERGY_SUSTAINABILITY("Renewable Energy", IndustryGroup.SUSTAINABILITY),
  SOLAR_SUSTAINABILITY("Solar", IndustryGroup.SUSTAINABILITY),
  SUSTAINABILITY("Sustainability", IndustryGroup.SUSTAINABILITY),
  WASTE_MANAGEMENT("Waste Management", IndustryGroup.SUSTAINABILITY),
  WATER_PURIFICATION("Water Purification", IndustryGroup.SUSTAINABILITY),
  WIND_ENERGY_SUSTAINABILITY("Wind Energy", IndustryGroup.SUSTAINABILITY),
  AIR_TRANSPORTATION("Air Transportation", IndustryGroup.TRANSPORTATION),
  AUTOMOTIVE("Automotive", IndustryGroup.TRANSPORTATION),
  AUTONOMOUS_VEHICLES("Autonomous Vehicles", IndustryGroup.TRANSPORTATION),
  CAR_SHARING("Car Sharing", IndustryGroup.TRANSPORTATION),
  COURIER_SERVICE_TRANSPORTATION("Courier Service", IndustryGroup.TRANSPORTATION),
  DELIVERY_SERVICE("Delivery Service", IndustryGroup.TRANSPORTATION),
  ELECTRIC_VEHICLE("Electric Vehicle", IndustryGroup.TRANSPORTATION),
  FERRY_SERVICE("Ferry Service", IndustryGroup.TRANSPORTATION),
  FLEET_MANAGEMENT("Fleet Management", IndustryGroup.TRANSPORTATION),
  FOOD_DELIVERY_TRANSPORTATION("Food Delivery", IndustryGroup.TRANSPORTATION),
  FREIGHT_SERVICE("Freight Service", IndustryGroup.TRANSPORTATION),
  LAST_MILE_TRANSPORTATION("Last Mile Transportation", IndustryGroup.TRANSPORTATION),
  LIMOUSINE_SERVICE("Limousine Service", IndustryGroup.TRANSPORTATION),
  LOGISTICS("Logistics", IndustryGroup.TRANSPORTATION),
  MARINE_TRANSPORTATION("Marine Transportation", IndustryGroup.TRANSPORTATION),
  PARKING("Parking", IndustryGroup.TRANSPORTATION),
  PORTS_AND_HARBORS("Ports and Harbors", IndustryGroup.TRANSPORTATION),
  PROCUREMENT("Procurement", IndustryGroup.TRANSPORTATION),
  PUBLIC_TRANSPORTATION("Public Transportation", IndustryGroup.TRANSPORTATION),
  RAILROAD("Railroad", IndustryGroup.TRANSPORTATION),
  RECREATIONAL_VEHICLES("Recreational Vehicles", IndustryGroup.TRANSPORTATION),
  RIDE_SHARING("Ride Sharing", IndustryGroup.TRANSPORTATION),
  SAME_DAY_DELIVERY("Same Day Delivery", IndustryGroup.TRANSPORTATION),
  SHIPPING("Shipping", IndustryGroup.TRANSPORTATION),
  SHIPPING_BROKER("Shipping Broker", IndustryGroup.TRANSPORTATION),
  SPACE_TRAVEL("Space Travel", IndustryGroup.TRANSPORTATION),
  SUPPLY_CHAIN_MANAGEMENT("Supply Chain Management", IndustryGroup.TRANSPORTATION),
  TAXI_SERVICE("Taxi Service", IndustryGroup.TRANSPORTATION),
  TRANSPORTATION("Transportation", IndustryGroup.TRANSPORTATION),
  WAREHOUSING("Warehousing", IndustryGroup.TRANSPORTATION),
  WATER_TRANSPORTATION("Water Transportation", IndustryGroup.TRANSPORTATION),
  ADVENTURE_TRAVEL("Adventure Travel", IndustryGroup.TRAVEL_AND_TOURISM),
  AMUSEMENT_PARK_AND_ARCADE("Amusement Park and Arcade", IndustryGroup.TRAVEL_AND_TOURISM),
  BUSINESS_TRAVEL("Business Travel", IndustryGroup.TRAVEL_AND_TOURISM),
  CASINO("Casino", IndustryGroup.TRAVEL_AND_TOURISM),
  HOSPITALITY("Hospitality", IndustryGroup.TRAVEL_AND_TOURISM),
  HOTEL("Hotel", IndustryGroup.TRAVEL_AND_TOURISM),
  MUSEUMS_AND_HISTORICAL_SITES("Museums and Historical Sites", IndustryGroup.TRAVEL_AND_TOURISM),
  PARKS("Parks", IndustryGroup.TRAVEL_AND_TOURISM),
  RESORTS("Resorts", IndustryGroup.TRAVEL_AND_TOURISM),
  TIMESHARE_TRAVEL("Timeshare", IndustryGroup.TRAVEL_AND_TOURISM),
  TOUR_OPERATOR("Tour Operator", IndustryGroup.TRAVEL_AND_TOURISM),
  TOURISM("Tourism", IndustryGroup.TRAVEL_AND_TOURISM),
  TRAVEL("Travel", IndustryGroup.TRAVEL_AND_TOURISM),
  TRAVEL_ACCOMMODATIONS("Travel Accommodations", IndustryGroup.TRAVEL_AND_TOURISM),
  TRAVEL_AGENCY("Travel Agency", IndustryGroup.TRAVEL_AND_TOURISM),
  VACATION_RENTAL_TRAVEL("Vacation Rental", IndustryGroup.TRAVEL_AND_TOURISM),
  ANIMATION_VIDEO("Animation", IndustryGroup.VIDEO),
  BROADCASTING_VIDEO("Broadcasting", IndustryGroup.VIDEO),
  FILM_VIDEO("Film", IndustryGroup.VIDEO),
  FILM_DISTRIBUTION_VIDEO("Film Distribution", IndustryGroup.VIDEO),
  FILM_PRODUCTION_VIDEO("Film Production", IndustryGroup.VIDEO),
  MOTION_CAPTURE_VIDEO("Motion Capture", IndustryGroup.VIDEO),
  TV_VIDEO("TV", IndustryGroup.VIDEO),
  TV_PRODUCTION_VIDEO("TV Production", IndustryGroup.VIDEO),
  VIDEO_VIDEO("Video", IndustryGroup.VIDEO),
  VIDEO_EDITING_VIDEO("Video Editing", IndustryGroup.VIDEO),
  VIDEO_ON_DEMAND_VIDEO("Video on Demand", IndustryGroup.VIDEO),
  VIDEO_STREAMING_VIDEO("Video Streaming", IndustryGroup.VIDEO);

  private final String name;
  private final String title;
  private final IndustryGroup group;

  Industry(String title, IndustryGroup group) {
    this.name = this.name();
    this.title = title;
    this.group = group;
  }
}
