package io.ventureplatform.entity.enums;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Getter;

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
@Getter
public enum MeasurementUnit implements DeserializableEnum {
  ALBANIAN_LEK("Albanian Lek", "ALL", "Lek"),
  AFGHAN_AFGHANI("Afghan Afghani", "AFN", "؋"),
  ARGENTINE_PESO("Argentine Peso", "ARS", "$"),
  ARUBAN_FLORIN_GUILDER("Aruban Florin Guilder", "AWG", "ƒ"),
  AUSTRALIAN_DOLLAR("Australian Dollar", "AUD", "$"),
  AZERBAIJANI_MANAT("Azerbaijani Manat", "AZN", "₼"),
  BAHAMIAN_DOLLAR("Bahamian Dollar", "BSD", "$"),
  BANGLADESHI_TAKA("Bangladeshi Taka", "BDT", "৳"),
  BARBADOS_DOLLAR("Barbados Dollar", "BBD", "$"),
  BELARUSIAN_RUBLE("Belarusian Ruble", "BYN", "Br"),
  BELIZE_DOLLAR("Belize Dollar", "BZD", "BZ$"),
  BERMUDIAN_DOLLAR("Bermudian Dollar", "BMD", "$"),
  BOLIVIAN_BOLIVIANO("Bolivian Bolíviano", "BOB", "$b"),
  BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK("Bosnia and Herzegovina Convertible Mark", "BAM", "KM"),
  BOTSWANA_PULA("Botswana Pula", "BWP", "P"),
  BRAZILIAN_REAL("Brazilian Real", "BRL", "R$"),
  BRUNEI_DOLLAR("Brunei Dollar", "BND", "$"),
  BULGARIAN_LEV("Bulgarian Lev", "BGN", "лв"),
  BURUNDIAN_FRANC("Burundian Franc", "BIF", "FBu"),
  CAMBODIAN_RIEL("Cambodian Riel", "KHR", "៛"),
  CANADIAN_DOLLAR("Canadian Dollar", "CAD", "$"),
  CAPE_VERDEAN_ESCUDO("Cape Verdean Escudo", "CVE", "$"),
  CAYMAN_ISLANDS_DOLLAR("Cayman Islands Dollar", "KYD", "$"),
  CENTRAL_AFRICAN_CFA_FRANC("Central African CFA Franc", "XAF", "FCFA"),
  CHILEAN_PESO("Chilean Peso", "CLP", "$"),
  CHINESE_YUAN_RENMINBI("Chinese Yuan Renminbi", "CNY", "¥"),
  COLOMBIAN_PESO("Colombian Peso", "COP", "$"),
  COMORIAN_FRANC("Comorian Franc", "KMF", "CF"),
  CONGOLESE_FRANC("Congolese Franc", "CDF", "FC"),
  COSTA_RICAN_COLON("Costa Rican Colón", "CRC", "₡"),
  CROATIAN_KUNA("Croatian Kuna", "HRK", "kn"),
  CUBAN_PESO("Cuban Peso", "CUP", "₱"),
  CZECH_KORUNA("Czech Koruna", "CZK", "Kč"),
  DANISH_KRONE("Danish Krone", "DKK", "kr"),
  DJIBOUTIAN_FRANC("Djiboutian Franc", "DJF", "Fdj"),
  DOMINICAN_REPUBLIC_PESO("Dominican Republic Peso", "DOP", "RD$"),
  EAST_CARIBBEAN_DOLLAR("East Caribbean Dollar", "XCD", "$"),
  EGYPTIAN_POUND("Egyptian Pound", "EGP", "£"),
  ERITREAN_NAKFA("Eritrean Nakfa", "ERN", "Nfk"),
  ETHIOPIAN_BIRR("Ethiopian Birr", "ETB", "Br"),
  EURO("Euro", "EUR", "€"),
  FALKLAND_ISLANDS_POUND("Falkland Islands Pound", "FKP", "£"),
  FIJIAN_DOLLAR("Fijian Dollar", "FJD", "$"),
  GAMBIAN_DALASI("Gambian Dalasi", "GMD", "D"),
  GEORGIAN_LARI("Georgian Lari", "GEL", "₾"),
  GHANAIAN_CEDI("Ghanaian Cedi", "GHS", "¢"),
  GIBRALTAR_POUND("Gibraltar Pound", "GIP", "£"),
  GREAT_BRITAIN_POUND("Pound sterling", "GBP", "£"),
  GUATEMALAN_QUETZAL("Guatemalan Quetzal", "GTQ", "Q"),
  GUINEAN_FRANC("Guinean Franc", "GNF", "FG"),
  GUYANESE_DOLLAR("Guyanese Dollar", "GYD", "$"),
  HAITIAN_GOURDE("Haitian Gourde", "HTG", "G"),
  HONDURAN_LEMPIRA("Honduran Lempira", "HNL", "L"),
  HONG_KONG_DOLLAR("Hong Kong Dollar", "HKD", "$"),
  HUNGARIAN_FORINT("Hungarian Forint", "HUF", "Ft"),
  ICELANDIC_KRONA("Icelandic Króna", "ISK", "kr"),
  INDIAN_RUPEE("Indian Rupee", "INR", "₹"),
  INDONESIAN_RUPIAH("Indonesian Rupiah", "IDR", "Rp"),
  IRANIAN_RIAL("Iranian Rial", "IRR", "﷼"),
  IRAQI_DINAR("Iraqi Dinar", "IQD", "ع.د"),
  ISRAELI_SHEKEL("Israeli Shekel", "ILS", "₪"),
  JAMAICAN_DOLLAR("Jamaican Dollar", "JMD", "J$"),
  JAPANESE_YEN("Japanese Yen", "JPY", "¥"),
  JORDANIAN_DINAR("Jordanian Dinar", "JOD", "JD"),
  KAZAKHSTANI_TENGE("Kazakhstani Tenge", "KZT", "лв"),
  KENYAN_SHILLING("Kenyan Shilling", "KES", "KSh"),
  KUWAITI_DINAR("Kuwaiti Dinar", "KWD", "KD"),
  KYRGYZSTANI_SOM("Kyrgyzstani Som", "KGS", "лв"),
  LAO_KIP("Lao Kip", "LAK", "₭"),
  LEBANESE_POUND("Lebanese Pound", "LBP", "£"),
  LESOTHO_LOTI("Lesotho Loti", "LSL", "L"),
  LIBERIAN_DOLLAR("Liberian Dollar", "LRD", "$"),
  LIBYAN_DINAR("Libyan Dinar", "LYD", "LD"),
  MACANESE_PATACA("Macanese Pataca", "MOP", "P"),
  MACEDONIAN_DENAR("Macedonian Denar", "MKD", "ден"),
  MALAGASY_ARIARY("Malagasy Ariary", "MGA", "Ar"),
  MALAWIAN_KWACHA("Malawian Kwacha", "MWK", "MK"),
  MALAYSIAN_RINGGIT("Malaysian Ringgit", "MYR", "RM"),
  MALDIVIAN_RUFIYAA("Maldivian Rufiyaa", "MVR", ".ރ"),
  MAURITANIAN_OUGUIYA("Mauritanian Ouguiya", "MRU", "UM"),
  MAURITIAN_RUPEE("Mauritian Rupee", "MUR", "₨"),
  MEXICAN_PESO("Mexican Peso", "MXN", "$"),
  MOLDOVAN_LEU("Moldovan Leu", "MDL", "L"),
  MONGOLIAN_TOGROG("Mongolian Tögrög", "MNT", "₮"),
  MOROCCAN_DIRHAM("Moroccan Dirham", "MAD", "د.م."),
  MOZAMBICAN_METICAL("Mozambican Metical", "MZN", "MT"),
  MYANMAR_KYAT("Myanmar Kyat", "MMK", "Ks."),
  NAMIBIAN_DOLLAR("Namibian Dollar", "NAD", "$"),
  NEPALESE_RUPEE("Nepalese Rupee", "NPR", "₨"),
  NETHERLANDS_ANTILLES_GUILDER("Netherlands Antilles Guilder", "ANG", "ƒ"),
  NEW_ZEALAND_DOLLAR("New Zealand Dollar", "NZD", "$"),
  NICARAGUAN_CORDOBA("Nicaraguan Córdoba", "NIO", "C$"),
  NIGERIAN_NAIRA("Nigerian Naira", "NGN", "₦"),
  NORTH_KOREAN_WON("North Korean Won", "KPW", "₩"),
  NORWEGIAN_KRONE("Norwegian Krone", "NOK", "kr"),
  OMANI_RIAL("Omani Rial", "OMR", "﷼"),
  PAKISTANI_RUPEE("Pakistani Rupee", "PKR", "₨"),
  PANAMANIAN_BALBOA("Panamanian Balboa", "PAB", "B/."),
  PAPUA_NEW_GUINEAN_KINA("Papua New Guinean Kina", "PGK", "K"),
  PARAGUAYAN_GUARANI("Paraguayan Guaraní", "PYG", "Gs"),
  PERUVIAN_SOL("Peruvian Sol", "PEN", "S/."),
  PHILIPPINE_PESO("Philippine Peso", "PHP", "₱"),
  POLISH_ZLOTY("Polish Złoty", "PLN", "zł"),
  QATARI_RIYAL("Qatari Riyal", "QAR", "﷼"),
  ROMANIAN_LEU("Romanian Leu", "RON", "lei"),
  RUSSIAN_RUBLE("Russian Ruble", "RUB", "₽"),
  RWANDAN_FRANC("Rwandan Franc", "RWF", "FRw"),
  SAINT_HELENA_POUND("Saint Helena Pound", "SHP", "£"),
  SALVADORAN_COLON("Salvadoran Colón", "SVC", "$"),
  SAMOAN_TALA("Samoan Tālā", "WST", "T"),
  SAO_TOME_AND_PRINCIPE_DOBRA("São Tomé and Príncipe Dobra", "STN", "Db"),
  SAUDI_RIYAL("Saudi Riyal", "SAR", "﷼"),
  SERBIAN_DINAR("Serbian Dinar", "RSD", "Дин."),
  SEYCHELLOIS_RUPEE("Seychellois Rupee", "SCR", "₨"),
  SIERRA_LEONEAN_LEONE("Sierra Leonean Leone", "SLL", "Le"),
  SINGAPORE_DOLLAR("Singapore Dollar", "SGD", "$"),
  SOLOMON_ISLANDS_DOLLAR("Solomon Islands Dollar", "SBD", "$"),
  SOMALI_SHILLING("Somali Shilling", "SOS", "S"),
  SOUTH_AFRICAN_RAND("South African Rand", "ZAR", "R"),
  SOUTH_KOREAN_WON("South Korean Won", "KRW", "₩"),
  SOUTH_SUDANESE_POUND("South Sudanese Pound", "SSP", "£"),
  SRI_LANKAN_RUPEE("Sri Lankan Rupee", "LKR", "Rs"),
  SUDANESE_POUND("Sudanese Pound", "SDG", "£"),
  SURINAMESE_DOLLAR("Surinamese Dollar", "SRD", "$"),
  SWAZI_LILANGENI("Swazi Lilangeni", "SZL", "L"),
  SWEDISH_KRONA("Swedish Krona", "SEK", "kr"),
  SWISS_FRANC("Swiss Franc", "CHF", "CHF"),
  SYRIAN_POUND("Syrian Pound", "SYP", "£"),
  TAIWANESE_NEW_DOLLAR("Taiwanese New Dollar", "TWD", "$"),
  TAJIKISTANI_SOMONI("Tajikistani Somoni", "TJS", "ЅМ"),
  TANZANIAN_SHILLING("Tanzanian Shilling", "TZS", "TSh"),
  THAI_BAHT("Thai Baht", "THB", "฿"),
  TONGAN_PAANGA("Tongan Paʻanga", "TOP", "T$"),
  TRINIDAD_AND_TOBAGO_DOLLAR("Trinidad and Tobago Dollar", "TTD", "$"),
  TUNISIAN_DINAR("Tunisian Dinar", "TND", "د.ت"),
  TURKISH_LIRA("Turkish Lira", "TRY", "₺"),
  TURKMENISTAN_MANAT("Turkmenistan Manat", "TMT", "m"),
  TUVALUAN_DOLLAR("Tuvaluan Dollar", "TVD", "$"),
  UGANDAN_SHILLING("Ugandan Shilling", "UGX", "USh"),
  UKRAINIAN_HRYVNIA("Ukrainian Hryvnia", "UAH", "₴"),
  UNITED_ARAB_EMIRATES_DIRHAM("United Arab Emirates Dirham", "AED", "د.إ"),
  UNITED_STATES_DOLLAR("United States Dollar", "USD", "$"),
  URUGUAYAN_PESO("Uruguayan Peso", "UYU", "$U"),
  UZBEKISTANI_SOM("Uzbekistani Som", "UZS", "лв"),
  VANUATU_VATU("Vanuatu Vatu", "VUV", "Vt"),
  VENEZUELAN_BOLIVAR_SOBERANO("Venezuelan Bolívar Soberano", "VES", "Bs. S"),
  VIETNAMESE_DONG("Vietnamese Đồng", "VND", "₫"),
  YEMENI_RIAL("Yemeni Rial", "YER", "﷼"),
  ZAMBIAN_KWACHA("Zambian Kwacha", "ZMW", "ZK"),
  ZIMBABWEAN_DOLLAR("Zimbabwean Dollar", "ZWL", "$"),
  PERCENTAGE("Percentage", null, "%"),
  SECOND("Second", null, "s"),
  MINUTE("Minute", null, "min"),
  HOUR("Hour", null, "h"),
  DAY("Day", null, "d"),
  WEEK("Week", null, "wk"),
  MONTH("Month", null, "mo"),
  YEAR("Year", null, "yr"),
  KILOGRAM("Kilogram", null, "kg"),
  GRAM("Gram", null, "g"),
  TONNE("Tonne", null, "t"),
  POUND("Pound", null, "lb"),
  FAHRENHEIT("Fahrenheit", null, "°F"),
  CELSIUS("Celsius", null, "°C"),
  KELVIN("Kelvin", null, "K"),
  KILOMETER("Kilometer", null, "km"),
  METER("Meter", null, "m"),
  MILE("Mile", null, "mi"),
  FOOT("Foot", null, "ft"),
  INCH("Inch", null, "in"),
  KILOGRAM_OF_CO2("Kilogram of CO2", null, "kg/CO2"),
  TON_OF_CO2("Ton of CO2", null, "t CO2"),
  KILOGRAM_OF_CO2_EQUIVALENT("Kilogram of CO2 equivalent", null, "kg CO2e"),
  TON_OF_CO2_EQUIVALENT("Ton of CO2 equivalent", null, "t CO2e"),
  METHANE("Methane", null, "CH4"),
  MILLILITER("Milliliter", null, "mL"),
  CENTILITER("Centiliter", null, "cL"),
  DECILITER("Deciliter", null, "dL"),
  LITER("Liter", null, "L"),
  HECTOLITER("Hectoliter", null, "hL"),
  CUBIC_METER("Cubic Meter", null, "m3"),
  CUBIC_DECIMETER("Cubic Decimeter", null, "dm3"),
  CUBIC_CENTIMETER("Cubic Centimeter", null, "cm3"),
  CUBIC_MILLIMETER("Cubic Millimeter", null, "mm3"),
  FLUID_OUNCE("Fluid Ounce", null, "fl oz"),
  PINT("Pint", null, "pt"),
  QUART("Quart", null, "qt"),
  GALLON("Gallon", null, "gal"),
  SQUARE_METER("Square meter", null, "sq2"),
  SQUARE_KILOMETER("Square kilometer", null, "km2"),
  KILOWATT_HOUR("Kilowatt-hour", null, "kWh"),
  MEGAWATT_HOUR("Megawatt-hour", null, "MWh"),
  GIGAWATT_HOUR("Gigawatt-hour", null, "GWh"),
  TERAWATT_HOUR("Terawatt-hour", null, "TWh"),
  PETAWATT_HOUR("Petawatt-hour", null, "PWh");

  private final String name;
  private final String label;
  private final String type;
  private final String isoCode;
  private final String symbol;

  MeasurementUnit(String label, String isoCode, String symbol) {
    this.type = this.getClass().getSimpleName();
    this.name = this.name();
    this.label = label;
    this.isoCode = isoCode;
    this.symbol = symbol;
  }
}
